import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function POST(request: NextRequest) {
  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { promptId, promptText, collaborators } = await request.json()

  if (!collaborators?.length) {
    return NextResponse.json({ error: 'No collaborators specified' }, { status: 400 })
  }

  // Get sender profile
  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name')
    .eq('id', user.id)
    .single()
  const senderName = profile?.full_name || 'Someone'

  const results = []
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://yourstruly.app'

  for (const collab of collaborators) {
    // Create the collaboration record (token auto-generated by DB default)
    const { data: invite, error } = await supabase
      .from('memory_collaborators')
      .insert({
        inviter_id: user.id,
        prompt_id: promptId,
        contact_id: collab.contactId.startsWith('email-') ? null : collab.contactId,
        contact_name: collab.name,
        contact_email: collab.email || null,
        prompt_text: promptText,
        story_context: `${senderName} is creating a memory and wants your perspective.`,
        status: 'pending',
      })
      .select('id, access_token')
      .single()

    if (error) {
      console.error('Failed to create collaboration invite:', error)
      continue
    }

    const collaborateLink = `${appUrl}/collaborate/${invite.access_token}`

    // Send email notification if email is available
    if (collab.email) {
      try {
        const resendKey = process.env.RESEND_API_KEY
        if (resendKey) {
          await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${resendKey}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              from: process.env.RESEND_FROM_EMAIL || 'YoursTruly <noreply@yourstruly.app>',
              to: collab.email,
              subject: `${senderName} invited you to add to a memory`,
              html: `
                <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 520px; margin: 0 auto; padding: 40px 24px;">
                  <div style="text-align: center; margin-bottom: 24px;">
                    <span style="font-size: 40px;">💌</span>
                  </div>
                  <h1 style="font-size: 22px; font-weight: 700; color: #1A1F1C; text-align: center; margin: 0 0 12px;">
                    ${senderName} wants your story
                  </h1>
                  <p style="font-size: 15px; color: #5A6660; text-align: center; margin: 0 0 8px; line-height: 1.5;">
                    They're capturing a memory and would love your perspective:
                  </p>
                  <div style="background: #F5F1EA; border-radius: 16px; padding: 20px; margin: 20px 0; text-align: center;">
                    <p style="font-size: 16px; font-weight: 600; color: #1A1F1C; margin: 0; font-style: italic;">
                      "${promptText}"
                    </p>
                  </div>
                  <div style="text-align: center; margin: 28px 0;">
                    <a href="${collaborateLink}" style="display: inline-block; padding: 14px 32px; background: #2D5A3D; color: white; text-decoration: none; border-radius: 12px; font-weight: 600; font-size: 15px;">
                      Add Your Story
                    </a>
                  </div>
                  <p style="font-size: 12px; color: #94A09A; text-align: center; margin: 24px 0 0;">
                    You'll be guided through a short conversation to share your perspective.
                  </p>
                </div>
              `,
            }),
          })

          // Update status to 'sent'
          await supabase
            .from('memory_collaborators')
            .update({ status: 'sent' })
            .eq('id', invite.id)
        }
      } catch (emailErr) {
        console.error('Email send failed:', emailErr)
      }
    }

    results.push({
      id: invite.id,
      name: collab.name,
      link: collaborateLink,
      status: collab.email ? 'sent' : 'pending',
    })
  }

  return NextResponse.json({ success: true, invites: results })
}
