-- ============================================================================
-- Seed 50 poignant prompts per chapter
--
-- Fills prompt_templates with 750 hand-written, reflective questions across
-- 15 chapters. Tone: warm, specific, sensory, satisfaction-invoking. Avoids
-- difficult/trauma topics — these are meant to make the user feel heard
-- and proud of the life they've lived.
--
-- Idempotent: INSERT ... WHERE NOT EXISTS dedupe on prompt_text so re-running
-- this migration is safe.
-- ============================================================================

WITH new_prompts (category, type, prompt_text, life_chapter) AS (VALUES

-- ── CHILDHOOD (50) ────────────────────────────────────────────────────────
('childhood','memory_prompt','What was the smell of your grandmother''s kitchen when dinner was cooking?','childhood'),
('childhood','memory_prompt','Which corner of your childhood home felt most like a hideaway?','childhood'),
('childhood','memory_prompt','Who taught you to tie your shoes, and where were you sitting?','childhood'),
('childhood','memory_prompt','What was the first song you remember dancing to?','childhood'),
('childhood','memory_prompt','What snack could your mom make that no one else could match?','childhood'),
('childhood','memory_prompt','Which toy stayed by your bed longer than any other?','childhood'),
('childhood','memory_prompt','Where did you go to feel like the whole world was yours?','childhood'),
('childhood','memory_prompt','What did your parents call you only when they were happy?','childhood'),
('childhood','memory_prompt','Which book did you want read to you over and over?','childhood'),
('childhood','memory_prompt','What sound meant summer was finally here?','childhood'),
('childhood','memory_prompt','Who was the neighborhood kid you spent the most time with?','childhood'),
('childhood','memory_prompt','What game did you invent with your siblings or friends?','childhood'),
('childhood','memory_prompt','Which adult outside your family made you feel truly seen?','childhood'),
('childhood','memory_prompt','What was your favorite spot to climb?','childhood'),
('childhood','memory_prompt','What did a perfect Saturday look like when you were seven?','childhood'),
('childhood','memory_prompt','Which holiday tradition do you still think about?','childhood'),
('childhood','memory_prompt','What''s the silliest rule your family had?','childhood'),
('childhood','memory_prompt','Where were you when you first learned to swim or ride a bike?','childhood'),
('childhood','memory_prompt','What did you want to be when you grew up at age five?','childhood'),
('childhood','memory_prompt','Which cartoon or show could glue you to the TV?','childhood'),
('childhood','memory_prompt','What did your mom or dad smell like when you hugged them?','childhood'),
('childhood','memory_prompt','What was the most magical thing you believed in as a kid?','childhood'),
('childhood','memory_prompt','Which meal meant something special was happening?','childhood'),
('childhood','memory_prompt','What was the first pet you remember, and what was their name?','childhood'),
('childhood','memory_prompt','Where was your favorite hiding spot during hide and seek?','childhood'),
('childhood','memory_prompt','What made your birthdays feel like the best day of the year?','childhood'),
('childhood','memory_prompt','Which song could your parents always be heard singing?','childhood'),
('childhood','memory_prompt','What was the bedtime ritual that made you feel safe?','childhood'),
('childhood','memory_prompt','Who was the grown-up who slipped you candy or treats?','childhood'),
('childhood','memory_prompt','What was the first movie you remember seeing in a theater?','childhood'),
('childhood','memory_prompt','Which playground piece did you always head for first?','childhood'),
('childhood','memory_prompt','What smell instantly brings childhood back to you?','childhood'),
('childhood','memory_prompt','What kind of mischief did you most often get into?','childhood'),
('childhood','memory_prompt','Who first taught you how to ride a bike?','childhood'),
('childhood','memory_prompt','What did your favorite stuffed animal look like?','childhood'),
('childhood','memory_prompt','Which chore did you secretly enjoy?','childhood'),
('childhood','memory_prompt','What was the best gift you ever received as a kid?','childhood'),
('childhood','memory_prompt','Where did the sun hit first in your house in the morning?','childhood'),
('childhood','memory_prompt','Which family member gave the best bear hugs?','childhood'),
('childhood','memory_prompt','What did rainy afternoons usually look like?','childhood'),
('childhood','memory_prompt','Which imaginary friend or game ran your imagination?','childhood'),
('childhood','memory_prompt','What''s a phrase your mom or dad said that you still hear?','childhood'),
('childhood','memory_prompt','What was your favorite ice cream flavor back then?','childhood'),
('childhood','memory_prompt','Who let you stay up past your bedtime without anyone knowing?','childhood'),
('childhood','memory_prompt','What was the first thing you remember being really proud of?','childhood'),
('childhood','memory_prompt','Which tree, park, or patch of grass was "yours"?','childhood'),
('childhood','memory_prompt','What food could you not stand, no matter what?','childhood'),
('childhood','memory_prompt','What''s something small that made you feel grown-up?','childhood'),
('childhood','memory_prompt','Who in your family always made you laugh the hardest?','childhood'),
('childhood','memory_prompt','What did the sound of your childhood house at night feel like?','childhood'),

-- ── TEENAGE (50) ──────────────────────────────────────────────────────────
('teenage','memory_prompt','What was the first song that made you feel understood?','teenage'),
('teenage','memory_prompt','Where did you and your friends go when there was nowhere to go?','teenage'),
('teenage','memory_prompt','Who was the friend you could talk to for hours without running out of things to say?','teenage'),
('teenage','memory_prompt','What did your bedroom walls look like?','teenage'),
('teenage','memory_prompt','Which teacher changed how you thought about yourself?','teenage'),
('teenage','memory_prompt','What was the style you worked way too hard to perfect?','teenage'),
('teenage','memory_prompt','What food did you and your friends always end up eating?','teenage'),
('teenage','memory_prompt','Which crush do you still smile about?','teenage'),
('teenage','memory_prompt','What was the first album you saved up to buy?','teenage'),
('teenage','memory_prompt','Where did you sit with your friends to feel at home?','teenage'),
('teenage','memory_prompt','What was the movie you watched more times than you can count?','teenage'),
('teenage','memory_prompt','Who did you try to impress most, and why?','teenage'),
('teenage','memory_prompt','What did driving somewhere by yourself for the first time feel like?','teenage'),
('teenage','memory_prompt','Which song instantly transports you back to that age?','teenage'),
('teenage','memory_prompt','What trend did you fully commit to that you now love remembering?','teenage'),
('teenage','memory_prompt','Who was the friend you always called first with good news?','teenage'),
('teenage','memory_prompt','Where was your favorite place to spend a summer night?','teenage'),
('teenage','memory_prompt','What made a Friday night feel legendary back then?','teenage'),
('teenage','memory_prompt','Which book cracked something open inside you?','teenage'),
('teenage','memory_prompt','What did you and your best friend laugh about until your stomachs hurt?','teenage'),
('teenage','memory_prompt','What was the first concert you went to?','teenage'),
('teenage','memory_prompt','Which outfit do you wish you still had photos of?','teenage'),
('teenage','memory_prompt','What was the sport, hobby, or club that defined you?','teenage'),
('teenage','memory_prompt','Who was the adult you looked up to outside your family?','teenage'),
('teenage','memory_prompt','What did a school dance actually feel like?','teenage'),
('teenage','memory_prompt','What was the first job or task that made you feel independent?','teenage'),
('teenage','memory_prompt','Where did you imagine you''d be in ten years?','teenage'),
('teenage','memory_prompt','Which late-night conversation do you still think about?','teenage'),
('teenage','memory_prompt','What kind of music did you secretly love?','teenage'),
('teenage','memory_prompt','What meal did you know how to make by yourself first?','teenage'),
('teenage','memory_prompt','Who was your partner in crime during those years?','teenage'),
('teenage','memory_prompt','What phrase or slang did everyone in your group say?','teenage'),
('teenage','memory_prompt','Where did you go when you needed to think?','teenage'),
('teenage','memory_prompt','What did you save your allowance or paycheck for?','teenage'),
('teenage','memory_prompt','Which teacher''s classroom felt like the safest place?','teenage'),
('teenage','memory_prompt','What was a small rebellion you were secretly proud of?','teenage'),
('teenage','memory_prompt','What did you believe about love at sixteen?','teenage'),
('teenage','memory_prompt','Which friend always cheered you up no matter what?','teenage'),
('teenage','memory_prompt','What was your absolute favorite snack after school?','teenage'),
('teenage','memory_prompt','Where did you picture yourself after high school?','teenage'),
('teenage','memory_prompt','What song did you play on repeat in your headphones?','teenage'),
('teenage','memory_prompt','What''s one thing you miss about being that age?','teenage'),
('teenage','memory_prompt','Which birthday during those years felt like a big deal?','teenage'),
('teenage','memory_prompt','What was the first thing you were ever really good at?','teenage'),
('teenage','memory_prompt','Who drove their car like it was a spaceship?','teenage'),
('teenage','memory_prompt','What was the best meal you shared with friends?','teenage'),
('teenage','memory_prompt','What did you write about in a journal or diary?','teenage'),
('teenage','memory_prompt','Which movie line did you and your friends quote constantly?','teenage'),
('teenage','memory_prompt','What''s a sound that instantly brings you back to those years?','teenage'),
('teenage','memory_prompt','What was the first time you realized you had a style of your own?','teenage'),

-- ── HIGH SCHOOL (50) ──────────────────────────────────────────────────────
('high_school','memory_prompt','Who sat next to you in your favorite class?','high_school'),
('high_school','memory_prompt','What did walking through the hallway feel like your first day?','high_school'),
('high_school','memory_prompt','Which lunch spot was your crew''s unofficial home?','high_school'),
('high_school','memory_prompt','What was your locker decoration situation?','high_school'),
('high_school','memory_prompt','Which teacher made you laugh even when you were tired?','high_school'),
('high_school','memory_prompt','What was the class that surprised you by becoming your favorite?','high_school'),
('high_school','memory_prompt','Who did you pass notes with?','high_school'),
('high_school','memory_prompt','What was the ritual before a big game, dance, or show?','high_school'),
('high_school','memory_prompt','What did the cafeteria smell like?','high_school'),
('high_school','memory_prompt','Which after-school activity kept you going?','high_school'),
('high_school','memory_prompt','What was the song on repeat at every school event?','high_school'),
('high_school','memory_prompt','Who walked with you between classes almost every day?','high_school'),
('high_school','memory_prompt','What was the first essay or project you were really proud of?','high_school'),
('high_school','memory_prompt','Which yearbook photo do you still love?','high_school'),
('high_school','memory_prompt','What was your routine before the first bell rang?','high_school'),
('high_school','memory_prompt','Who was the senior you looked up to when you were younger?','high_school'),
('high_school','memory_prompt','Which spot on campus felt magical after dark?','high_school'),
('high_school','memory_prompt','What did pep rallies actually feel like when the gym lit up?','high_school'),
('high_school','memory_prompt','Who was the classmate who surprised everyone with their talent?','high_school'),
('high_school','memory_prompt','What was the best field trip you ever went on?','high_school'),
('high_school','memory_prompt','What did your backpack look like by the end of the year?','high_school'),
('high_school','memory_prompt','Which class got you daydreaming out the window?','high_school'),
('high_school','memory_prompt','Who was the person you told first when something great happened?','high_school'),
('high_school','memory_prompt','What was the cafeteria food that was somehow always a favorite?','high_school'),
('high_school','memory_prompt','Which friend could you count on for notes when you missed class?','high_school'),
('high_school','memory_prompt','What was your go-to move to make your friends laugh?','high_school'),
('high_school','memory_prompt','Where did you eat lunch in the spring when the weather turned warm?','high_school'),
('high_school','memory_prompt','What was the school dance outfit you still remember?','high_school'),
('high_school','memory_prompt','Which sport game or performance do you still rewatch in your mind?','high_school'),
('high_school','memory_prompt','What was the strangest rule your school had?','high_school'),
('high_school','memory_prompt','Who was the friend you''d sit with on the bus?','high_school'),
('high_school','memory_prompt','What project or assignment made you realize you were capable?','high_school'),
('high_school','memory_prompt','Which crowd did you float between?','high_school'),
('high_school','memory_prompt','What was your senior year in one sentence?','high_school'),
('high_school','memory_prompt','Who wrote the funniest thing in your yearbook?','high_school'),
('high_school','memory_prompt','What song did your class pick as "your song"?','high_school'),
('high_school','memory_prompt','What was the best lunch trade you ever made?','high_school'),
('high_school','memory_prompt','Which locker-room or practice memory still makes you smile?','high_school'),
('high_school','memory_prompt','What was the first big decision you made for yourself in school?','high_school'),
('high_school','memory_prompt','Who walked the halls like they owned the place?','high_school'),
('high_school','memory_prompt','What did graduation day feel like from the moment you woke up?','high_school'),
('high_school','memory_prompt','Who was the first person you sat with on your first day?','high_school'),
('high_school','memory_prompt','What was the most memorable assembly or event?','high_school'),
('high_school','memory_prompt','Which club or team gave you the best people?','high_school'),
('high_school','memory_prompt','What was the smell of the school in early morning?','high_school'),
('high_school','memory_prompt','What did rainy days inside the building feel like?','high_school'),
('high_school','memory_prompt','Which friend always had snacks stashed in their locker?','high_school'),
('high_school','memory_prompt','What was the playlist that narrated your commute to school?','high_school'),
('high_school','memory_prompt','Who made you feel like you belonged when you didn''t yet?','high_school'),
('high_school','memory_prompt','What is the one thing you''d tell your high school self?','high_school'),

-- ── COLLEGE (50) ──────────────────────────────────────────────────────────
('college','memory_prompt','What did the first night in your dorm sound like?','college'),
('college','memory_prompt','Who did you become friends with surprisingly fast?','college'),
('college','memory_prompt','Which professor shifted the way you think?','college'),
('college','memory_prompt','What was your go-to late-night snack?','college'),
('college','memory_prompt','Where on campus did you go to feel grounded?','college'),
('college','memory_prompt','What was the class that accidentally changed your major or your mind?','college'),
('college','memory_prompt','Who was your first roommate?','college'),
('college','memory_prompt','What did your dorm room or apartment look like at its most lived-in?','college'),
('college','memory_prompt','Which all-nighter do you remember most fondly?','college'),
('college','memory_prompt','What was the first meal you cooked for yourself in college?','college'),
('college','memory_prompt','Which coffee shop or study spot was yours?','college'),
('college','memory_prompt','What was the best conversation you had at 2am?','college'),
('college','memory_prompt','Who did you sit next to on the first day of a class that mattered?','college'),
('college','memory_prompt','What was the first big trip or adventure during college?','college'),
('college','memory_prompt','Which tradition did your group of friends invent?','college'),
('college','memory_prompt','What was the job or internship that taught you something?','college'),
('college','memory_prompt','Who made your college life funnier than it needed to be?','college'),
('college','memory_prompt','What did a Sunday morning on campus feel like?','college'),
('college','memory_prompt','Which library, bookstore, or bench became yours?','college'),
('college','memory_prompt','What was the first paper or project you were truly proud of?','college'),
('college','memory_prompt','Who was your "ride or die" during those years?','college'),
('college','memory_prompt','What playlist defined a semester?','college'),
('college','memory_prompt','Which roommate still makes you laugh in retrospect?','college'),
('college','memory_prompt','What was the smell of your favorite dining hall meal?','college'),
('college','memory_prompt','Which decision during college did you feel in your gut was right?','college'),
('college','memory_prompt','Who did you call home about the most?','college'),
('college','memory_prompt','What was the first big idea that lit you up in a lecture?','college'),
('college','memory_prompt','Where did you go to celebrate after finals?','college'),
('college','memory_prompt','What did spring break look like for you?','college'),
('college','memory_prompt','Which friend taught you something you still use?','college'),
('college','memory_prompt','What was the silliest thing you and your friends did at 3am?','college'),
('college','memory_prompt','Who did you share meals with most often?','college'),
('college','memory_prompt','What was your favorite study-break tradition?','college'),
('college','memory_prompt','Which class did you never skip because it was that good?','college'),
('college','memory_prompt','What was the first concert or event you went to with college friends?','college'),
('college','memory_prompt','Which campus building felt magical at dusk?','college'),
('college','memory_prompt','What was a class you didn''t love at the time but appreciate now?','college'),
('college','memory_prompt','Who did you share your first real apartment with?','college'),
('college','memory_prompt','What was your favorite thing about campus in the fall?','college'),
('college','memory_prompt','Which semester do you wish you could relive?','college'),
('college','memory_prompt','What did graduation week feel like?','college'),
('college','memory_prompt','Who did you stand next to at graduation?','college'),
('college','memory_prompt','What was the last thing you did before leaving campus for good?','college'),
('college','memory_prompt','Which college friend do you still think of often?','college'),
('college','memory_prompt','What was the first thing you splurged on with your own money?','college'),
('college','memory_prompt','Who taught you how to really study?','college'),
('college','memory_prompt','What was your favorite route to walk between classes?','college'),
('college','memory_prompt','Which mentor or advisor steered you well?','college'),
('college','memory_prompt','What smell takes you right back to a dorm hallway?','college'),
('college','memory_prompt','What was the best hangout spot late at night?','college'),

-- ── JOBS & CAREER (50) ────────────────────────────────────────────────────
('jobs_career','memory_prompt','What was the first job that made you feel like a professional?','jobs_career'),
('jobs_career','memory_prompt','Who was the boss or mentor you still learn from in memory?','jobs_career'),
('jobs_career','memory_prompt','What was the first big project you were trusted with?','jobs_career'),
('jobs_career','memory_prompt','Which coworker became a real friend?','jobs_career'),
('jobs_career','memory_prompt','What did walking into your office for the first time feel like?','jobs_career'),
('jobs_career','memory_prompt','What was the first paycheck you remember spending?','jobs_career'),
('jobs_career','memory_prompt','Which workday felt the most meaningful?','jobs_career'),
('jobs_career','memory_prompt','Who taught you how to handle a hard conversation at work?','jobs_career'),
('jobs_career','memory_prompt','What was your go-to outfit for a big meeting?','jobs_career'),
('jobs_career','memory_prompt','Which work lunch spot became a tradition?','jobs_career'),
('jobs_career','memory_prompt','What was a small moment at work that made you feel proud?','jobs_career'),
('jobs_career','memory_prompt','Who was the person who believed in you before you believed in yourself?','jobs_career'),
('jobs_career','memory_prompt','What was the best job you ever interviewed for?','jobs_career'),
('jobs_career','memory_prompt','Which promotion or title meant the most to you?','jobs_career'),
('jobs_career','memory_prompt','What was the first time you taught someone at work?','jobs_career'),
('jobs_career','memory_prompt','Who was the customer or client who stays in your mind?','jobs_career'),
('jobs_career','memory_prompt','What was the moment you knew you were in the right field?','jobs_career'),
('jobs_career','memory_prompt','Which coworker made the hard days feel lighter?','jobs_career'),
('jobs_career','memory_prompt','What did your first desk or workspace look like?','jobs_career'),
('jobs_career','memory_prompt','Who surprised you with their talent or heart?','jobs_career'),
('jobs_career','memory_prompt','What was the best advice a boss ever gave you?','jobs_career'),
('jobs_career','memory_prompt','Which project taught you the most about yourself?','jobs_career'),
('jobs_career','memory_prompt','What did a "good day" at work look like in your prime?','jobs_career'),
('jobs_career','memory_prompt','Who did you mentor, and what did you learn from them?','jobs_career'),
('jobs_career','memory_prompt','What was the first skill you built that opened doors?','jobs_career'),
('jobs_career','memory_prompt','Which work trip was your favorite?','jobs_career'),
('jobs_career','memory_prompt','What did your morning routine for work look like at your favorite job?','jobs_career'),
('jobs_career','memory_prompt','Who was the office character everyone loved?','jobs_career'),
('jobs_career','memory_prompt','What was the funniest thing that ever happened at work?','jobs_career'),
('jobs_career','memory_prompt','Which email, letter, or call from a customer meant the most?','jobs_career'),
('jobs_career','memory_prompt','What was a small perk of a job you loved?','jobs_career'),
('jobs_career','memory_prompt','Who did you share your first "big" success with?','jobs_career'),
('jobs_career','memory_prompt','What was your favorite part of your daily work?','jobs_career'),
('jobs_career','memory_prompt','Which training or conference left a mark on you?','jobs_career'),
('jobs_career','memory_prompt','What was the first creative risk you took at work?','jobs_career'),
('jobs_career','memory_prompt','Who ate lunch with you the most over the years?','jobs_career'),
('jobs_career','memory_prompt','What was the ritual that signaled the end of the workday for you?','jobs_career'),
('jobs_career','memory_prompt','Which career milestone did you celebrate the biggest?','jobs_career'),
('jobs_career','memory_prompt','What was the first thing you learned you had a knack for?','jobs_career'),
('jobs_career','memory_prompt','Who gave you your first real shot?','jobs_career'),
('jobs_career','memory_prompt','What was the most unexpected job that turned out well?','jobs_career'),
('jobs_career','memory_prompt','Which part of your work did you find most rewarding?','jobs_career'),
('jobs_career','memory_prompt','What was a tradition your workplace had that you loved?','jobs_career'),
('jobs_career','memory_prompt','Who did you call first when you got your dream job?','jobs_career'),
('jobs_career','memory_prompt','What was the first tool of the trade you truly mastered?','jobs_career'),
('jobs_career','memory_prompt','Which decision in your career are you proud of?','jobs_career'),
('jobs_career','memory_prompt','What''s the work story you''ve told the most times?','jobs_career'),
('jobs_career','memory_prompt','Who still thanks you for something you did at work?','jobs_career'),
('jobs_career','memory_prompt','What was the best compliment a client or colleague ever gave you?','jobs_career'),
('jobs_career','memory_prompt','What did "a job well done" feel like to you?','jobs_career'),

-- ── RELATIONSHIPS (50) ────────────────────────────────────────────────────
('relationships','memory_prompt','Who do you call first when something great happens?','relationships'),
('relationships','memory_prompt','What was the first time you felt truly understood by someone?','relationships'),
('relationships','memory_prompt','Which friendship has aged the best over the years?','relationships'),
('relationships','memory_prompt','Who showed you what loyalty actually looks like?','relationships'),
('relationships','memory_prompt','What was the meal you shared with a close friend that felt special?','relationships'),
('relationships','memory_prompt','Who makes you feel like yourself just by being around?','relationships'),
('relationships','memory_prompt','What was the first gift from a friend you still treasure?','relationships'),
('relationships','memory_prompt','Who taught you how to be a good friend?','relationships'),
('relationships','memory_prompt','What was a tradition you and your best friend kept?','relationships'),
('relationships','memory_prompt','Who always made you laugh at the right moment?','relationships'),
('relationships','memory_prompt','What was the best letter or note a friend ever sent you?','relationships'),
('relationships','memory_prompt','Who are the people who feel like chosen family to you?','relationships'),
('relationships','memory_prompt','What was the road trip that turned into a lifelong memory?','relationships'),
('relationships','memory_prompt','Who was the friend who showed up without being asked?','relationships'),
('relationships','memory_prompt','What was the first sleepover or gathering you remember?','relationships'),
('relationships','memory_prompt','Who is the friend you can go years without talking to and pick right back up?','relationships'),
('relationships','memory_prompt','What did a perfect afternoon with friends look like?','relationships'),
('relationships','memory_prompt','Who was your first real confidant?','relationships'),
('relationships','memory_prompt','What did your friends call you as a nickname?','relationships'),
('relationships','memory_prompt','Who surprised you by becoming a forever friend?','relationships'),
('relationships','memory_prompt','What was a small kindness a friend showed you?','relationships'),
('relationships','memory_prompt','Who do you share the best inside jokes with?','relationships'),
('relationships','memory_prompt','What was the best trip with friends you''ve ever taken?','relationships'),
('relationships','memory_prompt','Who made you feel brave when you were nervous?','relationships'),
('relationships','memory_prompt','What was the last meaningful conversation you had with a friend?','relationships'),
('relationships','memory_prompt','Who was the friend who always had your back?','relationships'),
('relationships','memory_prompt','What was the tradition you invented together?','relationships'),
('relationships','memory_prompt','Who is the friend you laugh hardest with?','relationships'),
('relationships','memory_prompt','What did you and your closest friend bond over?','relationships'),
('relationships','memory_prompt','Who taught you how to listen well?','relationships'),
('relationships','memory_prompt','What was the best party a friend ever threw?','relationships'),
('relationships','memory_prompt','Who was your neighbor who became a friend?','relationships'),
('relationships','memory_prompt','What do your friends know about you that no one else does?','relationships'),
('relationships','memory_prompt','Who did you share your proudest moment with?','relationships'),
('relationships','memory_prompt','What was a ritual you kept with a friend for years?','relationships'),
('relationships','memory_prompt','Who made ordinary days feel special?','relationships'),
('relationships','memory_prompt','What was the first friendship that shaped who you became?','relationships'),
('relationships','memory_prompt','Who made you feel seen when you needed it most?','relationships'),
('relationships','memory_prompt','What does a friend of yours do better than anyone?','relationships'),
('relationships','memory_prompt','Who do you trust to tell the truth, gently?','relationships'),
('relationships','memory_prompt','What is a song that reminds you of a friend?','relationships'),
('relationships','memory_prompt','Who introduced you to something you now love?','relationships'),
('relationships','memory_prompt','What was the meal you shared the most laughter over?','relationships'),
('relationships','memory_prompt','Who is the friend you call when you just need to talk?','relationships'),
('relationships','memory_prompt','What small gesture did a friend once make that you never forgot?','relationships'),
('relationships','memory_prompt','Who do you share the best silences with?','relationships'),
('relationships','memory_prompt','What are you most grateful for in a friendship?','relationships'),
('relationships','memory_prompt','Who makes you feel at home when you''re with them?','relationships'),
('relationships','memory_prompt','What was a walk, hike, or drive that made a friendship deeper?','relationships'),
('relationships','memory_prompt','Who is the friend you wish you thanked more often?','relationships'),

-- ── TRAVEL (50) ───────────────────────────────────────────────────────────
('travel','memory_prompt','Where was the first trip that changed how you see the world?','travel'),
('travel','memory_prompt','What was the best meal you ever ate on a trip, and where?','travel'),
('travel','memory_prompt','Which view stopped you in your tracks?','travel'),
('travel','memory_prompt','Who did you take the best trip of your life with?','travel'),
('travel','memory_prompt','What was the most interesting place you stayed the night?','travel'),
('travel','memory_prompt','Which local custom did you fall in love with?','travel'),
('travel','memory_prompt','What did the air smell like when you first stepped off the plane or train?','travel'),
('travel','memory_prompt','What was the first place you traveled to that felt like home away from home?','travel'),
('travel','memory_prompt','Which city would you live in for a year if you could?','travel'),
('travel','memory_prompt','What was a small detail from a trip that you still remember?','travel'),
('travel','memory_prompt','Where did you feel the quietest?','travel'),
('travel','memory_prompt','What music did you listen to on that drive or flight?','travel'),
('travel','memory_prompt','Which stranger became a memorable part of a trip?','travel'),
('travel','memory_prompt','What was the best thing you bought on your travels?','travel'),
('travel','memory_prompt','Where did you go that surprised you the most?','travel'),
('travel','memory_prompt','Which morning on a trip was your favorite?','travel'),
('travel','memory_prompt','What was the first international meal you ever had?','travel'),
('travel','memory_prompt','Who made the best travel companion?','travel'),
('travel','memory_prompt','What''s a place you''d go back to in a heartbeat?','travel'),
('travel','memory_prompt','Which trip felt the most like an adventure?','travel'),
('travel','memory_prompt','What was the longest drive you''ve ever done, and where to?','travel'),
('travel','memory_prompt','Which sunset or sunrise left you speechless?','travel'),
('travel','memory_prompt','What was the best hotel or inn you stayed at?','travel'),
('travel','memory_prompt','Which local dish do you still crave?','travel'),
('travel','memory_prompt','What did walking through a foreign market feel like?','travel'),
('travel','memory_prompt','Where were you when you realized you were far from home and loving it?','travel'),
('travel','memory_prompt','What was the most beautiful place you''ve ever slept?','travel'),
('travel','memory_prompt','Who taught you something about the place you were visiting?','travel'),
('travel','memory_prompt','What was a tradition you picked up from another culture?','travel'),
('travel','memory_prompt','Which hike or walk do you still think about?','travel'),
('travel','memory_prompt','What was your most unexpected travel moment?','travel'),
('travel','memory_prompt','Where did you laugh the hardest on a trip?','travel'),
('travel','memory_prompt','What was the first souvenir you brought home?','travel'),
('travel','memory_prompt','Which place has the best people you''ve ever met?','travel'),
('travel','memory_prompt','Where were you when you took your favorite photo of a trip?','travel'),
('travel','memory_prompt','What was the quietest place you''ve ever been?','travel'),
('travel','memory_prompt','Which beach, lake, or river do you still feel on your skin?','travel'),
('travel','memory_prompt','What was the best conversation you had with a stranger while traveling?','travel'),
('travel','memory_prompt','Which museum or landmark moved you most?','travel'),
('travel','memory_prompt','What was the best meal a stranger welcomed you to?','travel'),
('travel','memory_prompt','Where would you take someone who''s never traveled?','travel'),
('travel','memory_prompt','What was the smallest, most perfect travel moment?','travel'),
('travel','memory_prompt','Which star-filled night sky do you still remember?','travel'),
('travel','memory_prompt','What was the best local guide''s story?','travel'),
('travel','memory_prompt','Where did you feel like you were walking through a postcard?','travel'),
('travel','memory_prompt','What did you bring home that still makes you smile?','travel'),
('travel','memory_prompt','Which trip changed something inside you?','travel'),
('travel','memory_prompt','What was the first time you tried a food you''d never heard of?','travel'),
('travel','memory_prompt','Where did you feel the most welcomed?','travel'),
('travel','memory_prompt','Which place still lives rent-free in your head?','travel'),

-- ── SPIRITUALITY (50) ─────────────────────────────────────────────────────
('spirituality','memory_prompt','What''s a tradition from your faith or beliefs that still grounds you?','spirituality'),
('spirituality','memory_prompt','Who introduced you to what you believe?','spirituality'),
('spirituality','memory_prompt','What song or hymn still moves you?','spirituality'),
('spirituality','memory_prompt','Where do you feel most at peace?','spirituality'),
('spirituality','memory_prompt','What''s a prayer, meditation, or ritual you return to?','spirituality'),
('spirituality','memory_prompt','Which teacher, elder, or guide shaped your spiritual path?','spirituality'),
('spirituality','memory_prompt','What does a quiet morning of reflection look like for you?','spirituality'),
('spirituality','memory_prompt','Which sacred place have you visited that stayed with you?','spirituality'),
('spirituality','memory_prompt','What was the first spiritual experience you remember?','spirituality'),
('spirituality','memory_prompt','Who prays for you or thinks of you with love?','spirituality'),
('spirituality','memory_prompt','What does gratitude look like in your daily life?','spirituality'),
('spirituality','memory_prompt','Which book or text has shaped your beliefs most?','spirituality'),
('spirituality','memory_prompt','What''s a tradition from childhood you''ve kept with you?','spirituality'),
('spirituality','memory_prompt','What meal, practice, or ritual feels sacred to you?','spirituality'),
('spirituality','memory_prompt','Where do you go to feel small and held?','spirituality'),
('spirituality','memory_prompt','Which moment in nature felt spiritual to you?','spirituality'),
('spirituality','memory_prompt','What''s a phrase or verse that comforts you?','spirituality'),
('spirituality','memory_prompt','What''s the most loving thing someone ever did for you?','spirituality'),
('spirituality','memory_prompt','Which holiday or observance means the most to you?','spirituality'),
('spirituality','memory_prompt','What do you believe about the people who''ve shaped you?','spirituality'),
('spirituality','memory_prompt','When do you feel most connected to something larger?','spirituality'),
('spirituality','memory_prompt','Who introduced you to silence as a practice?','spirituality'),
('spirituality','memory_prompt','What''s a song you''ve sung in celebration?','spirituality'),
('spirituality','memory_prompt','Which ceremony, service, or gathering still glows in your memory?','spirituality'),
('spirituality','memory_prompt','What does your practice look like on ordinary days?','spirituality'),
('spirituality','memory_prompt','Who is the elder you loved sitting with?','spirituality'),
('spirituality','memory_prompt','What''s a lesson your faith or beliefs taught you?','spirituality'),
('spirituality','memory_prompt','Which morning or evening light feels sacred?','spirituality'),
('spirituality','memory_prompt','What''s a ritual you share with someone you love?','spirituality'),
('spirituality','memory_prompt','What do you believe about kindness?','spirituality'),
('spirituality','memory_prompt','Who taught you to listen to your inner voice?','spirituality'),
('spirituality','memory_prompt','What does "home" mean to your spirit?','spirituality'),
('spirituality','memory_prompt','Which small daily habit feels holy to you?','spirituality'),
('spirituality','memory_prompt','What tradition would you pass to children in your family?','spirituality'),
('spirituality','memory_prompt','What''s the most peaceful place you''ve ever prayed or meditated?','spirituality'),
('spirituality','memory_prompt','Who models compassion for you?','spirituality'),
('spirituality','memory_prompt','What''s a moment of awe you''ve had this year?','spirituality'),
('spirituality','memory_prompt','Which story from your faith do you love most?','spirituality'),
('spirituality','memory_prompt','What do you believe you were made for?','spirituality'),
('spirituality','memory_prompt','Who is someone whose goodness you still feel?','spirituality'),
('spirituality','memory_prompt','What''s a small miracle you remember?','spirituality'),
('spirituality','memory_prompt','Which holy day felt most alive?','spirituality'),
('spirituality','memory_prompt','What does "enough" mean to you spiritually?','spirituality'),
('spirituality','memory_prompt','Who reminds you to slow down?','spirituality'),
('spirituality','memory_prompt','What''s a tradition around food that carries meaning?','spirituality'),
('spirituality','memory_prompt','Which song of thanks do you hum?','spirituality'),
('spirituality','memory_prompt','What do you turn to when you need to reset?','spirituality'),
('spirituality','memory_prompt','Who gave you a blessing you still carry?','spirituality'),
('spirituality','memory_prompt','What''s a practice that keeps you anchored?','spirituality'),
('spirituality','memory_prompt','What does reverence feel like to you?','spirituality'),

-- ── WISDOM & LEGACY (50) ──────────────────────────────────────────────────
('wisdom_legacy','knowledge','What''s the best piece of advice you''ve ever given?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you want your grandchildren to know about you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a lesson life took its time teaching you?','wisdom_legacy'),
('wisdom_legacy','knowledge','Which value do you most hope to pass on?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the one thing you''ve always been certain about?','wisdom_legacy'),
('wisdom_legacy','knowledge','What would you tell your younger self on their wedding day?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about forgiveness?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a small lesson you use almost every day?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you know now that you wish you''d known at 25?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a habit that has served you well for years?','wisdom_legacy'),
('wisdom_legacy','knowledge','Which person is responsible for who you are today?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the kindest thing a stranger ever did for you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you believe about hard work?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the best thing that ever happened to you by accident?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about love that surprised you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a small rule you''ve made for yourself that matters?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the best gift you''ve ever given someone?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you want people to remember you for?','wisdom_legacy'),
('wisdom_legacy','knowledge','What would you say in a toast to your own life so far?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s something you do every day that feels important?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the wisest thing you ever overheard?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about patience?','wisdom_legacy'),
('wisdom_legacy','knowledge','Who do you see in yourself when you look in the mirror?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a decision you''re proud you made?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about listening?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the most beautiful thing about growing older?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you believe is worth doing well?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a tradition you want to live on after you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the best compliment anyone has paid you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you think makes a good life?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you want to be sure to say to the people you love?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about trust?','wisdom_legacy'),
('wisdom_legacy','knowledge','Which achievement still makes you smile?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a book or piece of art that changed you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the best thing you cook, and who taught you?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you know about gratitude that took you years to learn?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a secret to happiness you''d share?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about how to treat people?','wisdom_legacy'),
('wisdom_legacy','knowledge','Who do you want to thank, who you''ve never told?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the best thing you''ve done for a stranger?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you think you were put here to do?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a lesson you learned from your parents you still use?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s a rule you''ve broken that you don''t regret?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s your definition of success now, versus at 30?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the best birthday you ever had?','wisdom_legacy'),
('wisdom_legacy','knowledge','What have you learned about honest conversation?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you love about the person you''ve become?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the most fun you''ve ever had?','wisdom_legacy'),
('wisdom_legacy','knowledge','What''s the smallest moment you most want remembered?','wisdom_legacy'),
('wisdom_legacy','knowledge','What do you want carved, quietly, on the memory of your life?','wisdom_legacy'),

-- ── LIFE MOMENTS (50) ─────────────────────────────────────────────────────
('life_moments','memory_prompt','What was the best morning you''ve ever woken up to?','life_moments'),
('life_moments','memory_prompt','Which phone call made your whole day?','life_moments'),
('life_moments','memory_prompt','What was the first time you realized you were happy?','life_moments'),
('life_moments','memory_prompt','Which celebration do you still describe to people?','life_moments'),
('life_moments','memory_prompt','What''s a moment when someone said yes and everything changed?','life_moments'),
('life_moments','memory_prompt','Which "best day" still holds up?','life_moments'),
('life_moments','memory_prompt','What''s a moment when a stranger made you feel seen?','life_moments'),
('life_moments','memory_prompt','Which sunrise or sunset are you holding onto?','life_moments'),
('life_moments','memory_prompt','What was your proudest moment as a parent, partner, or friend?','life_moments'),
('life_moments','memory_prompt','Which handwritten note still lives in a drawer somewhere?','life_moments'),
('life_moments','memory_prompt','What was the first time a piece of music moved you to tears?','life_moments'),
('life_moments','memory_prompt','Which hug do you remember most vividly?','life_moments'),
('life_moments','memory_prompt','What''s a dinner that became a memory?','life_moments'),
('life_moments','memory_prompt','Which spontaneous moment turned into something you love?','life_moments'),
('life_moments','memory_prompt','What was the moment you knew you were in love?','life_moments'),
('life_moments','memory_prompt','Which unexpected compliment still makes you smile?','life_moments'),
('life_moments','memory_prompt','What''s a day you''d happily live over and over?','life_moments'),
('life_moments','memory_prompt','Which birthday stands out above all the others?','life_moments'),
('life_moments','memory_prompt','What was the moment you felt most alive?','life_moments'),
('life_moments','memory_prompt','Which photo of yourself do you love?','life_moments'),
('life_moments','memory_prompt','What''s a "wow" moment you want to hold onto?','life_moments'),
('life_moments','memory_prompt','Which small gesture meant more than you expected?','life_moments'),
('life_moments','memory_prompt','What was the first time you felt brave?','life_moments'),
('life_moments','memory_prompt','Which anniversary felt most meaningful?','life_moments'),
('life_moments','memory_prompt','What''s a moment where everything just clicked?','life_moments'),
('life_moments','memory_prompt','Which song was playing during your favorite memory?','life_moments'),
('life_moments','memory_prompt','What was the first time you felt truly generous?','life_moments'),
('life_moments','memory_prompt','Which laugh do you want captured forever?','life_moments'),
('life_moments','memory_prompt','What''s a moment when you felt the world was good?','life_moments'),
('life_moments','memory_prompt','Which "first" do you still glow about?','life_moments'),
('life_moments','memory_prompt','What was the best weekend you ever had?','life_moments'),
('life_moments','memory_prompt','Which stranger''s kindness do you still think about?','life_moments'),
('life_moments','memory_prompt','What''s the best thing you''ve ever received in the mail?','life_moments'),
('life_moments','memory_prompt','Which quiet moment do you cherish?','life_moments'),
('life_moments','memory_prompt','What was the first time you saw your own strength?','life_moments'),
('life_moments','memory_prompt','Which visit home felt extra sweet?','life_moments'),
('life_moments','memory_prompt','What''s a moment you wish you had on video?','life_moments'),
('life_moments','memory_prompt','Which surprise moved you the most?','life_moments'),
('life_moments','memory_prompt','What was the best toast you''ve ever heard?','life_moments'),
('life_moments','memory_prompt','Which reunion meant the most?','life_moments'),
('life_moments','memory_prompt','What was a day where the weather was somehow perfect?','life_moments'),
('life_moments','memory_prompt','Which moment made you feel grown up?','life_moments'),
('life_moments','memory_prompt','What''s the best homecoming you''ve experienced?','life_moments'),
('life_moments','memory_prompt','Which recent moment do you already know you''ll remember for years?','life_moments'),
('life_moments','memory_prompt','What was the best conversation you had at a dinner table?','life_moments'),
('life_moments','memory_prompt','Which quiet Sunday do you still remember?','life_moments'),
('life_moments','memory_prompt','What was the first time a small kindness made your whole week?','life_moments'),
('life_moments','memory_prompt','Which unexpected gift do you still own?','life_moments'),
('life_moments','memory_prompt','What was a moment when you felt totally at peace?','life_moments'),
('life_moments','memory_prompt','Which moment do you think of when you need to smile?','life_moments'),

-- ── FAMILY (50) ───────────────────────────────────────────────────────────
('family','memory_prompt','What''s a Sunday at home that still warms you?','family'),
('family','memory_prompt','Which family member always made holidays special?','family'),
('family','memory_prompt','What''s a dish at the family table that no one else can match?','family'),
('family','memory_prompt','Who in your family tells the best stories?','family'),
('family','memory_prompt','What''s a tradition that only your family does?','family'),
('family','memory_prompt','Who did you run to when you skinned your knee?','family'),
('family','memory_prompt','What''s a family road trip you still remember?','family'),
('family','memory_prompt','Who taught you how to do something you do well now?','family'),
('family','memory_prompt','What does your family laugh about the most?','family'),
('family','memory_prompt','Which family photo is your favorite?','family'),
('family','memory_prompt','Who was the quiet one whose love you still feel?','family'),
('family','memory_prompt','What''s the most comforting thing your mom or dad ever said?','family'),
('family','memory_prompt','Who in your family are you most like?','family'),
('family','memory_prompt','Which family gathering felt like a movie?','family'),
('family','memory_prompt','What''s a phrase your grandparents used that you still say?','family'),
('family','memory_prompt','Which relative did you most look up to?','family'),
('family','memory_prompt','What was the best family vacation?','family'),
('family','memory_prompt','Who always brought the best dessert?','family'),
('family','memory_prompt','Which birthday with family stands out?','family'),
('family','memory_prompt','What''s the silliest family argument about a small thing?','family'),
('family','memory_prompt','Who in your family has the best singing voice?','family'),
('family','memory_prompt','What''s the best meal you ever shared at home?','family'),
('family','memory_prompt','Who taught you to cook, even if it was just one thing?','family'),
('family','memory_prompt','Which family member could make anyone feel welcome?','family'),
('family','memory_prompt','What''s a family inside joke you still laugh at?','family'),
('family','memory_prompt','Who did you share a room with growing up?','family'),
('family','memory_prompt','What does Sunday dinner at your house look like?','family'),
('family','memory_prompt','Which family tradition will you keep forever?','family'),
('family','memory_prompt','Who in your family is the peacemaker?','family'),
('family','memory_prompt','What''s your earliest memory of your siblings or cousins?','family'),
('family','memory_prompt','Who in your family gave the most generous hugs?','family'),
('family','memory_prompt','Which relative had the best garden, workshop, or kitchen?','family'),
('family','memory_prompt','What''s the story your family tells about you when you were little?','family'),
('family','memory_prompt','Who taught you how to drive?','family'),
('family','memory_prompt','What''s your favorite photo of your parents together?','family'),
('family','memory_prompt','Which family holiday do you wish you could have again?','family'),
('family','memory_prompt','Who is the youngest family member who surprises you with their wisdom?','family'),
('family','memory_prompt','What''s a lesson a grandparent taught you?','family'),
('family','memory_prompt','Which family celebration do you still talk about?','family'),
('family','memory_prompt','Who always cheers for you the loudest?','family'),
('family','memory_prompt','What''s a song that feels like family to you?','family'),
('family','memory_prompt','Which family recipe would you want to pass on?','family'),
('family','memory_prompt','Who gave you the best piece of advice about family?','family'),
('family','memory_prompt','What''s a small tradition your parents kept that meant a lot?','family'),
('family','memory_prompt','Who did you look for in the crowd at school events?','family'),
('family','memory_prompt','What''s the best thing about being part of your family?','family'),
('family','memory_prompt','Which relative calls just to check in?','family'),
('family','memory_prompt','What does "home" mean when you think of your family?','family'),
('family','memory_prompt','Who is the heart of your family?','family'),
('family','memory_prompt','What''s something your family does that feels sacred?','family'),

-- ── MARRIAGE (50) ─────────────────────────────────────────────────────────
('marriage','memory_prompt','When did you know they were "the one"?','marriage'),
('marriage','memory_prompt','What''s a small ritual you and your partner share?','marriage'),
('marriage','memory_prompt','Where was your first date?','marriage'),
('marriage','memory_prompt','What song plays as "your song" for the two of you?','marriage'),
('marriage','memory_prompt','What''s something your partner cooks better than anyone?','marriage'),
('marriage','memory_prompt','What''s a favorite thing about how they laugh?','marriage'),
('marriage','memory_prompt','What''s a look they give you that you love?','marriage'),
('marriage','memory_prompt','What was the moment you asked them to marry you, or they asked you?','marriage'),
('marriage','memory_prompt','What does a perfect Saturday look like with them?','marriage'),
('marriage','memory_prompt','What''s something they do every day that you appreciate?','marriage'),
('marriage','memory_prompt','Where was your first trip together?','marriage'),
('marriage','memory_prompt','What''s the best gift they''ve ever given you?','marriage'),
('marriage','memory_prompt','What do they do that no one else in the world could do?','marriage'),
('marriage','memory_prompt','What''s your favorite photo of them?','marriage'),
('marriage','memory_prompt','What was your wedding day moment you still play back?','marriage'),
('marriage','memory_prompt','What''s a habit of theirs you secretly love?','marriage'),
('marriage','memory_prompt','What''s something they taught you?','marriage'),
('marriage','memory_prompt','Where do you two go when you need to be alone together?','marriage'),
('marriage','memory_prompt','What do you call each other when no one''s around?','marriage'),
('marriage','memory_prompt','What was the first meal you cooked together?','marriage'),
('marriage','memory_prompt','What''s the thing you trust them with most?','marriage'),
('marriage','memory_prompt','What anniversary stands out?','marriage'),
('marriage','memory_prompt','What''s a silly argument that became a running joke?','marriage'),
('marriage','memory_prompt','What''s something they do that still surprises you?','marriage'),
('marriage','memory_prompt','What was your honeymoon like?','marriage'),
('marriage','memory_prompt','What did they look like the first time you saw them?','marriage'),
('marriage','memory_prompt','What''s a small gesture they do that means the world?','marriage'),
('marriage','memory_prompt','What''s the best meal you''ve shared?','marriage'),
('marriage','memory_prompt','What''s the bravest thing they''ve ever done?','marriage'),
('marriage','memory_prompt','What''s a tradition you started together?','marriage'),
('marriage','memory_prompt','What do you love about the way they move through the world?','marriage'),
('marriage','memory_prompt','What''s the best day you''ve had together recently?','marriage'),
('marriage','memory_prompt','What''s a song that reminds you of falling in love?','marriage'),
('marriage','memory_prompt','What did you wear on a date you still remember?','marriage'),
('marriage','memory_prompt','What''s the best thing about being on the same team?','marriage'),
('marriage','memory_prompt','What do you both laugh at that no one else would find funny?','marriage'),
('marriage','memory_prompt','What''s something they taught you to appreciate?','marriage'),
('marriage','memory_prompt','What''s your favorite place to walk together?','marriage'),
('marriage','memory_prompt','What do you love about watching them with family?','marriage'),
('marriage','memory_prompt','What''s a silly ritual you have?','marriage'),
('marriage','memory_prompt','What''s the best thing they''ve ever made with their hands?','marriage'),
('marriage','memory_prompt','What''s a moment when they really showed up for you?','marriage'),
('marriage','memory_prompt','What does "home" feel like when they''re in it?','marriage'),
('marriage','memory_prompt','What''s the best thing you''ve built together?','marriage'),
('marriage','memory_prompt','What do you want to say to them that you rarely do?','marriage'),
('marriage','memory_prompt','What''s your favorite thing to do on a weeknight together?','marriage'),
('marriage','memory_prompt','What''s a future memory you can''t wait to make with them?','marriage'),
('marriage','memory_prompt','What''s their best story, in your opinion?','marriage'),
('marriage','memory_prompt','What do you love about the way they love you?','marriage'),
('marriage','memory_prompt','What do you want to remember about your life with them?','marriage'),

-- ── HOBBIES (50) ──────────────────────────────────────────────────────────
('hobbies','memory_prompt','What hobby do you lose track of time doing?','hobbies'),
('hobbies','memory_prompt','What''s the first tool or gear you bought for a hobby you love?','hobbies'),
('hobbies','memory_prompt','Who introduced you to it?','hobbies'),
('hobbies','memory_prompt','What''s the best moment you''ve had doing it?','hobbies'),
('hobbies','memory_prompt','What do you wish more people understood about it?','hobbies'),
('hobbies','memory_prompt','Where do you do it when you want to be alone?','hobbies'),
('hobbies','memory_prompt','What''s the first thing you made or completed?','hobbies'),
('hobbies','memory_prompt','Who do you share this hobby with?','hobbies'),
('hobbies','memory_prompt','What''s your favorite place to buy supplies, books, or gear?','hobbies'),
('hobbies','memory_prompt','What''s the best story your hobby has in it?','hobbies'),
('hobbies','memory_prompt','What''s a small mastery that still makes you proud?','hobbies'),
('hobbies','memory_prompt','What''s the hobby that stuck when others didn''t?','hobbies'),
('hobbies','memory_prompt','What''s a song, book, or show that feels part of it?','hobbies'),
('hobbies','memory_prompt','What''s the best thing you''ve ever made as a gift?','hobbies'),
('hobbies','memory_prompt','Who taught you a trick you still use?','hobbies'),
('hobbies','memory_prompt','What''s the most unexpected lesson this hobby taught you?','hobbies'),
('hobbies','memory_prompt','What''s the smell or sound that means "I''m doing my thing"?','hobbies'),
('hobbies','memory_prompt','Where''s the best place you''ve practiced your hobby?','hobbies'),
('hobbies','memory_prompt','What''s the thing you can''t wait to try next?','hobbies'),
('hobbies','memory_prompt','What''s a piece of gear you love more than you should?','hobbies'),
('hobbies','memory_prompt','Who''s the best person you''ve learned from?','hobbies'),
('hobbies','memory_prompt','What''s a project that took forever but was worth it?','hobbies'),
('hobbies','memory_prompt','What season is the best for your hobby?','hobbies'),
('hobbies','memory_prompt','What do you love about doing it on a rainy day?','hobbies'),
('hobbies','memory_prompt','What''s the most scenic place you''ve enjoyed it?','hobbies'),
('hobbies','memory_prompt','What''s the first competition, show, or share you ever did?','hobbies'),
('hobbies','memory_prompt','What has this hobby taught you about patience?','hobbies'),
('hobbies','memory_prompt','Who in your life was surprised you were good at this?','hobbies'),
('hobbies','memory_prompt','What''s something you''ve made that turned out better than expected?','hobbies'),
('hobbies','memory_prompt','What''s your favorite piece from your collection?','hobbies'),
('hobbies','memory_prompt','Who in your family shares this hobby?','hobbies'),
('hobbies','memory_prompt','What''s the best compliment you''ve ever received on your work?','hobbies'),
('hobbies','memory_prompt','What''s a mistake that turned into something cool?','hobbies'),
('hobbies','memory_prompt','What''s your favorite playlist for doing it?','hobbies'),
('hobbies','memory_prompt','What''s the hobby you always wanted to start?','hobbies'),
('hobbies','memory_prompt','Who in your life would you love to teach?','hobbies'),
('hobbies','memory_prompt','What''s the first thing you do when you sit down to work on it?','hobbies'),
('hobbies','memory_prompt','What''s the best hack or tip you''ve learned?','hobbies'),
('hobbies','memory_prompt','What''s your favorite time of day to do it?','hobbies'),
('hobbies','memory_prompt','What''s a small ritual you have around it?','hobbies'),
('hobbies','memory_prompt','What did your first attempt look like?','hobbies'),
('hobbies','memory_prompt','What''s a moment when it really did calm your mind?','hobbies'),
('hobbies','memory_prompt','What''s the most unusual place you''ve taken your hobby?','hobbies'),
('hobbies','memory_prompt','What''s the best community or group for it?','hobbies'),
('hobbies','memory_prompt','What''s the oldest item in your hobby drawer or workshop?','hobbies'),
('hobbies','memory_prompt','What hobby would you pick up if you had another life?','hobbies'),
('hobbies','memory_prompt','What''s the most surprising benefit you''ve gotten from it?','hobbies'),
('hobbies','memory_prompt','What''s something you made that still hangs in your home?','hobbies'),
('hobbies','memory_prompt','Who is a person you think of every time you do it?','hobbies'),
('hobbies','memory_prompt','What does doing your hobby feel like in your best moments?','hobbies'),

-- ── FIRSTS (50) ───────────────────────────────────────────────────────────
('firsts','memory_prompt','What''s your first memory?','firsts'),
('firsts','memory_prompt','What was your first friend''s name?','firsts'),
('firsts','memory_prompt','What was the first thing you ever saved up to buy?','firsts'),
('firsts','memory_prompt','What was your first real meal out without your parents?','firsts'),
('firsts','memory_prompt','What was your first pet?','firsts'),
('firsts','memory_prompt','What was the first place you ever drove yourself to?','firsts'),
('firsts','memory_prompt','What was the first concert you ever attended?','firsts'),
('firsts','memory_prompt','What was the first book that made you fall in love with reading?','firsts'),
('firsts','memory_prompt','What was the first dance you remember going to?','firsts'),
('firsts','memory_prompt','What was your first job?','firsts'),
('firsts','memory_prompt','What was the first time you cooked a meal by yourself?','firsts'),
('firsts','memory_prompt','What was the first trip without your family?','firsts'),
('firsts','memory_prompt','What was the first song you ever memorized?','firsts'),
('firsts','memory_prompt','What was your first bike like?','firsts'),
('firsts','memory_prompt','What was the first time you flew on a plane?','firsts'),
('firsts','memory_prompt','What was the first paycheck you remember?','firsts'),
('firsts','memory_prompt','What was your first home away from home?','firsts'),
('firsts','memory_prompt','What was the first movie that made you cry?','firsts'),
('firsts','memory_prompt','What was your first kiss like, honestly?','firsts'),
('firsts','memory_prompt','What was the first game you loved playing?','firsts'),
('firsts','memory_prompt','What was the first thing you cooked that turned out well?','firsts'),
('firsts','memory_prompt','What was the first compliment you remember getting as an adult?','firsts'),
('firsts','memory_prompt','What was the first car that was "yours"?','firsts'),
('firsts','memory_prompt','What was the first time you felt truly independent?','firsts'),
('firsts','memory_prompt','What was the first friend you introduced to your family?','firsts'),
('firsts','memory_prompt','What was the first thing you bought with your own paycheck?','firsts'),
('firsts','memory_prompt','What was your first neighborhood like?','firsts'),
('firsts','memory_prompt','What was the first time you tried a food you''d never heard of?','firsts'),
('firsts','memory_prompt','What was the first sports event you remember?','firsts'),
('firsts','memory_prompt','What was the first time you made someone laugh really hard?','firsts'),
('firsts','memory_prompt','What was the first thing you were nervous to try but did anyway?','firsts'),
('firsts','memory_prompt','What was the first time you helped a stranger?','firsts'),
('firsts','memory_prompt','What was the first time your opinion was really asked for?','firsts'),
('firsts','memory_prompt','What was the first creative thing you made on your own?','firsts'),
('firsts','memory_prompt','What was the first poem, song, or story you wrote?','firsts'),
('firsts','memory_prompt','What was the first time you realized you were good at something?','firsts'),
('firsts','memory_prompt','What was the first piece of art you owned?','firsts'),
('firsts','memory_prompt','What was the first real conversation you had with a grandparent?','firsts'),
('firsts','memory_prompt','What was your first apartment like?','firsts'),
('firsts','memory_prompt','What was the first time you fell asleep outdoors?','firsts'),
('firsts','memory_prompt','What was the first team you were ever on?','firsts'),
('firsts','memory_prompt','What was the first language you learned a word of beyond your native?','firsts'),
('firsts','memory_prompt','What was the first "grown-up" purchase you made?','firsts'),
('firsts','memory_prompt','What was the first time you went somewhere alone and loved it?','firsts'),
('firsts','memory_prompt','What was the first moment of parenting that amazed you?','firsts'),
('firsts','memory_prompt','What was the first moment you felt like an adult?','firsts'),
('firsts','memory_prompt','What was the first gift you ever bought for your mom or dad?','firsts'),
('firsts','memory_prompt','What was the first time you felt lucky?','firsts'),
('firsts','memory_prompt','What was the first time a meal tasted like home?','firsts'),
('firsts','memory_prompt','What was the first time you knew you''d be okay?','firsts'),

-- ── LIFE LESSONS (50) ─────────────────────────────────────────────────────
('life_lessons','knowledge','What lesson took you the longest to learn?','life_lessons'),
('life_lessons','knowledge','Who taught you the most important thing about being kind?','life_lessons'),
('life_lessons','knowledge','What''s a rule you live by?','life_lessons'),
('life_lessons','knowledge','What''s the best advice you''ve given someone recently?','life_lessons'),
('life_lessons','knowledge','What do you believe is worth slowing down for?','life_lessons'),
('life_lessons','knowledge','What lesson did travel teach you that a book never could?','life_lessons'),
('life_lessons','knowledge','What''s a truth you''d hand-write on a card?','life_lessons'),
('life_lessons','knowledge','What have you learned about listening?','life_lessons'),
('life_lessons','knowledge','What have you learned about starting something new?','life_lessons'),
('life_lessons','knowledge','What''s a small habit that changed your life?','life_lessons'),
('life_lessons','knowledge','What have you learned about saying no gracefully?','life_lessons'),
('life_lessons','knowledge','What''s something you thought was important at 20 that isn''t now?','life_lessons'),
('life_lessons','knowledge','What have you learned about apologizing well?','life_lessons'),
('life_lessons','knowledge','What do you know about friendship that took years?','life_lessons'),
('life_lessons','knowledge','What have you learned about when to speak up?','life_lessons'),
('life_lessons','knowledge','What''s a life hack that''s also a life lesson?','life_lessons'),
('life_lessons','knowledge','What have you learned about handling a long day?','life_lessons'),
('life_lessons','knowledge','What do you know now about money that you wish you knew younger?','life_lessons'),
('life_lessons','knowledge','What have you learned about being on time?','life_lessons'),
('life_lessons','knowledge','What did a mentor teach you that stuck?','life_lessons'),
('life_lessons','knowledge','What have you learned about being kind to yourself?','life_lessons'),
('life_lessons','knowledge','What do you know about raising kids, even if just from watching?','life_lessons'),
('life_lessons','knowledge','What''s a phrase you repeat to yourself?','life_lessons'),
('life_lessons','knowledge','What have you learned about asking for help?','life_lessons'),
('life_lessons','knowledge','What''s the best rule you''ve made about your own time?','life_lessons'),
('life_lessons','knowledge','What do you know about resting well?','life_lessons'),
('life_lessons','knowledge','What have you learned about letting small things go?','life_lessons'),
('life_lessons','knowledge','What do you know about cooking for people you love?','life_lessons'),
('life_lessons','knowledge','What have you learned about being patient with yourself?','life_lessons'),
('life_lessons','knowledge','What do you know about keeping a promise?','life_lessons'),
('life_lessons','knowledge','What have you learned about celebrating small wins?','life_lessons'),
('life_lessons','knowledge','What''s the best reminder you put on your phone or fridge?','life_lessons'),
('life_lessons','knowledge','What have you learned about being curious?','life_lessons'),
('life_lessons','knowledge','What do you know about keeping a friendship alive?','life_lessons'),
('life_lessons','knowledge','What have you learned about owning a mistake?','life_lessons'),
('life_lessons','knowledge','What''s the best thing you''ve learned about laughter?','life_lessons'),
('life_lessons','knowledge','What have you learned about saying thank you?','life_lessons'),
('life_lessons','knowledge','What do you know about showing up for people?','life_lessons'),
('life_lessons','knowledge','What have you learned about the word "enough"?','life_lessons'),
('life_lessons','knowledge','What do you know about keeping your word?','life_lessons'),
('life_lessons','knowledge','What have you learned about giving without keeping score?','life_lessons'),
('life_lessons','knowledge','What''s a life lesson you learned from a child?','life_lessons'),
('life_lessons','knowledge','What have you learned about being gentle?','life_lessons'),
('life_lessons','knowledge','What do you know about reading a room?','life_lessons'),
('life_lessons','knowledge','What have you learned about being brave about small things?','life_lessons'),
('life_lessons','knowledge','What do you know about beginning again?','life_lessons'),
('life_lessons','knowledge','What have you learned about finding joy in routine?','life_lessons'),
('life_lessons','knowledge','What do you know about being a good guest?','life_lessons'),
('life_lessons','knowledge','What have you learned about being a good host?','life_lessons'),
('life_lessons','knowledge','What''s the one lesson you''d write on the first page of your life''s book?','life_lessons')
)
INSERT INTO prompt_templates (category, type, prompt_text, is_active, priority_boost, life_chapter)
SELECT
  np.category,
  np.type::prompt_type,
  np.prompt_text,
  TRUE,
  0,
  np.life_chapter
FROM new_prompts np
WHERE NOT EXISTS (
  SELECT 1 FROM prompt_templates pt WHERE pt.prompt_text = np.prompt_text
);

COMMENT ON TABLE prompt_templates IS 'Hand-curated engagement prompts. 750+ reflective questions across 15 chapters as of 20260410.';
