-- Tokens that let mobile devices upload media into a user's account
-- Generated by authenticated web clients, scanned via QR code on phone.
CREATE TABLE IF NOT EXISTS mobile_upload_tokens (
    token TEXT PRIMARY KEY,
    user_id UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mobile_upload_tokens_user ON mobile_upload_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_mobile_upload_tokens_expires ON mobile_upload_tokens(expires_at);
