-- Migration: Seed the prompt_seed_library with 500 curated prompts
-- Tier 0 Universal (50) + Tier 0 Anchored (80) + Tier 1 (100) + Tier 2 (120) + Tier 3 (100) + Tier 4 (50) = 500

-- =============================================================
-- TIER 0 — Universal Seeds (50 prompts)
-- Easy, warm, no data needed. Every new user sees these first.
-- =============================================================

INSERT INTO prompt_seed_library (tier, text, anchor, placeholders, category, angle, requires, anti_repeat_group, snowball_hooks, sort_order) VALUES

-- place
(0, 'What''s a place you''ve been that you still think about from time to time?', NULL, '{}', 'travel', 'place', '{}', 'favorite_place', '{travel,nostalgia}', 1),
(0, 'What did your neighborhood look like when you were ten?', NULL, '{}', 'childhood', 'place', '{}', 'childhood_place', '{childhood,neighborhood,home}', 2),
(0, 'Where''s the most unexpected place you''ve ever felt completely at home?', NULL, '{}', 'belonging', 'place', '{}', 'unexpected_home', '{belonging,travel}', 3),
(0, 'What''s a place you keep meaning to go back to but haven''t yet?', NULL, '{}', 'travel', 'place', '{}', 'return_place', '{travel,longing}', 4),
(0, 'If you could walk through any building from your past one more time, which would it be?', NULL, '{}', 'nostalgia', 'place', '{}', 'building_memory', '{nostalgia,architecture}', 5),
(0, 'What''s a street or road you could still navigate with your eyes closed?', NULL, '{}', 'familiarity', 'place', '{}', 'familiar_road', '{childhood,routine}', 6),
(0, 'Where were you the last time you felt truly peaceful?', NULL, '{}', 'emotion', 'place', '{}', 'peaceful_place', '{peace,retreat}', 7),
(0, 'What''s a place that doesn''t exist anymore but you can still picture perfectly?', NULL, '{}', 'memory', 'place', '{}', 'vanished_place', '{nostalgia,loss}', 8),

-- feeling
(0, 'Think of a sound from your childhood — what memory does it bring back?', NULL, '{}', 'sensory', 'feeling', '{}', 'childhood_sound', '{childhood,sensory}', 9),
(0, 'What''s a meal that means more to you than just food?', NULL, '{}', 'food', 'feeling', '{}', 'meaningful_meal', '{food,family,tradition}', 10),
(0, 'What smell instantly takes you back to a specific moment?', NULL, '{}', 'sensory', 'feeling', '{}', 'smell_memory', '{sensory,nostalgia}', 11),
(0, 'What''s the most content you''ve ever felt doing something completely ordinary?', NULL, '{}', 'contentment', 'feeling', '{}', 'ordinary_joy', '{peace,simplicity}', 12),
(0, 'What''s something that always makes you laugh, no matter how many times it happens?', NULL, '{}', 'humor', 'feeling', '{}', 'reliable_laugh', '{humor,joy}', 13),
(0, 'What song do you associate with a specific period of your life?', NULL, '{}', 'music', 'feeling', '{}', 'song_memory', '{music,era,nostalgia}', 14),
(0, 'What''s the kindest thing a stranger ever did for you?', NULL, '{}', 'kindness', 'feeling', '{}', 'stranger_kindness', '{kindness,gratitude}', 15),
(0, 'What''s a feeling you had as a kid that you wish you could get back?', NULL, '{}', 'childhood', 'feeling', '{}', 'childhood_feeling', '{childhood,innocence}', 16),

-- event
(0, 'What''s something you know how to do that most people don''t?', NULL, '{}', 'skills', 'event', '{}', 'unique_skill', '{skills,identity}', 17),
(0, 'What''s a photo you wish you''d taken but didn''t — what was happening?', NULL, '{}', 'regret', 'event', '{}', 'missed_photo', '{photography,moment}', 18),
(0, 'What''s the best day you''ve had that you didn''t plan at all?', NULL, '{}', 'spontaneity', 'event', '{}', 'unplanned_day', '{spontaneity,joy}', 19),
(0, 'What''s a small decision you made that ended up changing everything?', NULL, '{}', 'decisions', 'event', '{}', 'small_decision', '{decisions,fate}', 20),
(0, 'What''s the hardest thing you''ve ever done that you''re glad you did?', NULL, '{}', 'resilience', 'event', '{}', 'hard_but_glad', '{resilience,growth}', 21),
(0, 'What''s a trip or adventure that didn''t go as planned but became a great story?', NULL, '{}', 'adventure', 'event', '{}', 'misadventure', '{travel,humor,resilience}', 22),
(0, 'What''s the first big thing you ever did completely on your own?', NULL, '{}', 'independence', 'event', '{}', 'first_solo', '{independence,growing_up}', 23),
(0, 'What''s an ordinary day from your past that you remember in surprising detail?', NULL, '{}', 'memory', 'event', '{}', 'vivid_ordinary', '{memory,detail}', 24),

-- people
(0, 'Who''s someone who changed the direction of your life without knowing it?', NULL, '{}', 'influence', 'people', '{}', 'unknown_influence', '{influence,gratitude}', 25),
(0, 'Who taught you something that had nothing to do with school?', NULL, '{}', 'mentors', 'people', '{}', 'life_teacher', '{mentors,lessons}', 26),
(0, 'Who''s someone you haven''t talked to in years but still think about?', NULL, '{}', 'lost_touch', 'people', '{}', 'lost_touch', '{longing,friendship}', 27),
(0, 'What''s something your mom or dad always said that turned out to be right?', NULL, '{}', 'family', 'people', '{}', 'parent_wisdom', '{family,wisdom}', 28),
(0, 'Who''s the funniest person you''ve ever known?', NULL, '{}', 'humor', 'people', '{}', 'funniest_person', '{humor,friendship}', 29),
(0, 'Who''s someone you wish you could introduce to each other from different parts of your life?', NULL, '{}', 'relationships', 'people', '{}', 'crossover_intro', '{friendship,connections}', 30),
(0, 'Who believed in you before you believed in yourself?', NULL, '{}', 'support', 'people', '{}', 'early_believer', '{support,confidence}', 31),
(0, 'What''s the best advice anyone ever gave you — and did you take it?', NULL, '{}', 'wisdom', 'people', '{}', 'best_advice', '{wisdom,decisions}', 32),

-- object
(0, 'What''s an object you''ve kept for years that most people would throw away?', NULL, '{}', 'keepsakes', 'object', '{}', 'kept_object', '{keepsakes,sentiment}', 33),
(0, 'What''s something you own that tells a story no one else would guess?', NULL, '{}', 'possessions', 'object', '{}', 'story_object', '{possessions,stories}', 34),
(0, 'What''s a book, movie, or album that hit you differently than you expected?', NULL, '{}', 'culture', 'object', '{}', 'unexpected_media', '{culture,surprise}', 35),
(0, 'What''s the most sentimental thing in your wallet, bag, or pocket right now?', NULL, '{}', 'everyday', 'object', '{}', 'pocket_sentiment', '{everyday,sentiment}', 36),
(0, 'What''s something you made with your own hands that you''re still proud of?', NULL, '{}', 'creation', 'object', '{}', 'handmade_pride', '{creation,skills}', 37),
(0, 'What''s a gift you received that meant more than the person who gave it probably realized?', NULL, '{}', 'gifts', 'object', '{}', 'meaningful_gift', '{gifts,gratitude}', 38),
(0, 'If your house were on fire and everyone was safe, what one thing would you grab?', NULL, '{}', 'priorities', 'object', '{}', 'fire_grab', '{priorities,sentiment}', 39),
(0, 'What''s a piece of clothing that reminds you of a specific time in your life?', NULL, '{}', 'fashion', 'object', '{}', 'clothing_memory', '{fashion,era,nostalgia}', 40),

-- turning_point
(0, 'What''s a turning point in your life that didn''t feel like one at the time?', NULL, '{}', 'reflection', 'turning_point', '{}', 'hidden_turning', '{reflection,hindsight}', 41),
(0, 'What''s something you used to be afraid of that doesn''t scare you anymore?', NULL, '{}', 'growth', 'turning_point', '{}', 'conquered_fear', '{growth,courage}', 42),
(0, 'What age were you when you first felt like an adult — and what triggered it?', NULL, '{}', 'growing_up', 'turning_point', '{}', 'first_adult', '{growing_up,identity}', 43),
(0, 'What''s a belief you held strongly that you''ve since completely changed your mind about?', NULL, '{}', 'perspective', 'turning_point', '{}', 'changed_belief', '{perspective,growth}', 44),
(0, 'What''s the moment you realized what you wanted to do with your life — or stopped caring about having one answer?', NULL, '{}', 'purpose', 'turning_point', '{}', 'life_direction', '{purpose,identity}', 45),
(0, 'What''s a goodbye that was harder than you expected?', NULL, '{}', 'loss', 'turning_point', '{}', 'hard_goodbye', '{loss,love}', 46),
(0, 'When did you first realize your parents were just people figuring it out too?', NULL, '{}', 'family', 'turning_point', '{}', 'parents_human', '{family,empathy,growing_up}', 47),
(0, 'What''s something that ended — a job, a friendship, a chapter — that turned out to be exactly what needed to happen?', NULL, '{}', 'endings', 'turning_point', '{}', 'necessary_ending', '{endings,growth,acceptance}', 48),
(0, 'What''s a risk you almost didn''t take that ended up being worth it?', NULL, '{}', 'courage', 'turning_point', '{}', 'worthy_risk', '{courage,decisions}', 49),
(0, 'What''s a moment that split your life into a before and after?', NULL, '{}', 'milestones', 'turning_point', '{}', 'before_after', '{milestones,transformation}', 50);


-- =============================================================
-- TIER 0 — Onboarding-Anchored Templates (80 prompts)
-- 16 per anchor: place, person, interest, why_here, era
-- =============================================================

-- anchor='place' (16 prompts)
INSERT INTO prompt_seed_library (tier, text, anchor, placeholders, category, angle, requires, anti_repeat_group, snowball_hooks, sort_order) VALUES
(0, 'You lived in {place} — what''s the first thing you''d show someone visiting for the first time?', 'place', '{place}', 'hometown', 'place', '{has_places}', 'hometown_intro', '{hometown,neighborhood}', 51),
(0, 'What did {place} smell like? Not the tourist version — the real one.', 'place', '{place}', 'sensory', 'feeling', '{has_places}', 'place_smell', '{sensory,hometown}', 52),
(0, 'Who''s someone from {place} you lost touch with but still wonder about?', 'place', '{place}', 'connections', 'people', '{has_places}', 'place_person_lost', '{friendship,hometown}', 53),
(0, 'What''s a spot in {place} that probably doesn''t exist anymore but you can still picture perfectly?', 'place', '{place}', 'nostalgia', 'place', '{has_places}', 'vanished_spot', '{nostalgia,change}', 54),
(0, 'What was your favorite time of day in {place}?', 'place', '{place}', 'routine', 'feeling', '{has_places}', 'place_time_of_day', '{routine,peace}', 55),
(0, 'What''s something about {place} that only someone who lived there would know?', 'place', '{place}', 'insider', 'place', '{has_places}', 'place_insider', '{local,secrets}', 56),
(0, 'What''s the weather in {place} that you remember most vividly?', 'place', '{place}', 'sensory', 'feeling', '{has_places}', 'place_weather', '{weather,sensory,seasons}', 57),
(0, 'Where did you go in {place} when you needed to be alone?', 'place', '{place}', 'solitude', 'place', '{has_places}', 'place_alone_spot', '{solitude,retreat}', 58),
(0, 'What was the food in {place} that you couldn''t get anywhere else?', 'place', '{place}', 'food', 'object', '{has_places}', 'place_food', '{food,hometown,nostalgia}', 59),
(0, 'What''s a sound you associate with {place} that you don''t hear anymore?', 'place', '{place}', 'sensory', 'feeling', '{has_places}', 'place_sound', '{sensory,nostalgia,loss}', 60),
(0, 'If you went back to {place} tomorrow, what''s the first thing you''d do?', 'place', '{place}', 'return', 'event', '{has_places}', 'place_return', '{return,nostalgia}', 61),
(0, 'What did home feel like in {place} — not the building, the feeling?', 'place', '{place}', 'belonging', 'feeling', '{has_places}', 'place_home_feeling', '{belonging,comfort}', 62),
(0, 'Who was your neighbor in {place}, and what do you remember about them?', 'place', '{place}', 'community', 'people', '{has_places}', 'place_neighbor', '{community,characters}', 63),
(0, 'What''s a holiday or tradition that was unique to life in {place}?', 'place', '{place}', 'traditions', 'event', '{has_places}', 'place_tradition', '{traditions,culture}', 64),
(0, 'What did you learn about yourself by living in {place}?', 'place', '{place}', 'growth', 'turning_point', '{has_places}', 'place_lesson', '{growth,identity}', 65),
(0, 'What''s the story of how you ended up in {place} in the first place?', 'place', '{place}', 'origins', 'event', '{has_places}', 'place_origin_story', '{origins,decisions}', 66),

-- anchor='person' (16 prompts)
(0, 'Tell me about a time {person_name} surprised you — not a birthday surprise, just something they did that caught you off guard.', 'person', '{person_name}', 'relationships', 'people', '{has_contacts}', 'person_surprise', '{surprise,character}', 67),
(0, 'What''s something {person_name} taught you without meaning to?', 'person', '{person_name}', 'lessons', 'people', '{has_contacts}', 'person_lesson', '{lessons,influence}', 68),
(0, 'If {person_name} described you to a stranger, what would they say first?', 'person', '{person_name}', 'identity', 'people', '{has_contacts}', 'person_describes_you', '{identity,perspective}', 69),
(0, 'What''s the funniest thing that ever happened between you and {person_name}?', 'person', '{person_name}', 'humor', 'people', '{has_contacts}', 'person_funny', '{humor,bonding}', 70),
(0, 'What''s a moment with {person_name} that felt small at the time but stayed with you?', 'person', '{person_name}', 'moments', 'feeling', '{has_contacts}', 'person_small_moment', '{moments,significance}', 71),
(0, 'What''s the first memory that comes to mind when you think of {person_name}?', 'person', '{person_name}', 'memory', 'people', '{has_contacts}', 'person_first_memory', '{memory,association}', 72),
(0, 'What''s something {person_name} always said or did that was unmistakably them?', 'person', '{person_name}', 'character', 'people', '{has_contacts}', 'person_signature', '{character,identity}', 73),
(0, 'What''s a meal, a trip, or a day you shared with {person_name} that you''d love to relive?', 'person', '{person_name}', 'experiences', 'event', '{has_contacts}', 'person_relive', '{experiences,nostalgia}', 74),
(0, 'How did you and {person_name} first meet — do you remember the moment?', 'person', '{person_name}', 'origins', 'event', '{has_contacts}', 'person_meeting', '{origins,beginnings}', 75),
(0, 'What''s something you and {person_name} disagree about but it doesn''t matter?', 'person', '{person_name}', 'dynamics', 'people', '{has_contacts}', 'person_disagree', '{dynamics,acceptance}', 76),
(0, 'What''s a hard time {person_name} helped you through?', 'person', '{person_name}', 'support', 'people', '{has_contacts}', 'person_support', '{support,gratitude}', 77),
(0, 'What would you want {person_name} to know that you''ve never actually said?', 'person', '{person_name}', 'unsaid', 'feeling', '{has_contacts}', 'person_unsaid', '{unsaid,vulnerability}', 78),
(0, 'What''s a tradition or inside joke you share with {person_name}?', 'person', '{person_name}', 'bonding', 'event', '{has_contacts}', 'person_tradition', '{bonding,humor}', 79),
(0, 'How has your relationship with {person_name} changed over the years?', 'person', '{person_name}', 'evolution', 'turning_point', '{has_contacts}', 'person_evolution', '{evolution,growth}', 80),
(0, 'What''s a way {person_name} is different from how most people see them?', 'person', '{person_name}', 'depth', 'people', '{has_contacts}', 'person_hidden_side', '{depth,perception}', 81),
(0, 'If you had to describe {person_name} in one scene — not words, a scene — what would it be?', 'person', '{person_name}', 'character', 'people', '{has_contacts}', 'person_scene', '{character,storytelling}', 82),

-- anchor='interest' (16 prompts)
(0, 'You said you''re into {interest} — was there a moment it went from something you tried to something that''s part of who you are?', 'interest', '{interest}', 'identity', 'turning_point', '{has_interests}', 'interest_origin', '{identity,passion}', 83),
(0, 'Who''s the person most responsible for your love of {interest}?', 'interest', '{interest}', 'influence', 'people', '{has_interests}', 'interest_influencer', '{influence,gratitude}', 84),
(0, 'What would a perfect day involving {interest} look like for you?', 'interest', '{interest}', 'dreams', 'event', '{has_interests}', 'interest_perfect_day', '{dreams,joy}', 85),
(0, 'What''s something about {interest} that most people don''t appreciate or understand?', 'interest', '{interest}', 'passion', 'feeling', '{has_interests}', 'interest_misunderstood', '{passion,knowledge}', 86),
(0, 'What''s the best conversation you''ve ever had about {interest}?', 'interest', '{interest}', 'connection', 'people', '{has_interests}', 'interest_conversation', '{connection,ideas}', 87),
(0, 'What''s a memory tied to {interest} that still gives you energy when you think about it?', 'interest', '{interest}', 'energy', 'feeling', '{has_interests}', 'interest_energy', '{energy,passion}', 88),
(0, 'Has {interest} ever connected you with someone you wouldn''t have met otherwise?', 'interest', '{interest}', 'connection', 'people', '{has_interests}', 'interest_connection', '{connection,serendipity}', 89),
(0, 'What''s the first thing you ever made, did, or experienced related to {interest}?', 'interest', '{interest}', 'beginnings', 'event', '{has_interests}', 'interest_first_time', '{beginnings,nostalgia}', 90),
(0, 'If you could share {interest} with one person from your past, who would it be and why?', 'interest', '{interest}', 'sharing', 'people', '{has_interests}', 'interest_share', '{sharing,connection}', 91),
(0, 'What''s a time {interest} helped you through a difficult period?', 'interest', '{interest}', 'comfort', 'feeling', '{has_interests}', 'interest_comfort', '{comfort,coping}', 92),
(0, 'What''s the biggest mistake or failure you''ve had with {interest}, and what did you learn?', 'interest', '{interest}', 'growth', 'event', '{has_interests}', 'interest_failure', '{growth,resilience}', 93),
(0, 'Where does {interest} take you — physically or mentally — that nothing else does?', 'interest', '{interest}', 'escape', 'place', '{has_interests}', 'interest_escape', '{escape,flow}', 94),
(0, 'What''s something you''ve collected, built, or created through {interest} that you''re proud of?', 'interest', '{interest}', 'achievement', 'object', '{has_interests}', 'interest_creation', '{achievement,pride}', 95),
(0, 'How has your relationship with {interest} changed since you first started?', 'interest', '{interest}', 'evolution', 'turning_point', '{has_interests}', 'interest_evolution', '{evolution,depth}', 96),
(0, 'What''s the most surprising thing {interest} has taught you about yourself?', 'interest', '{interest}', 'self_discovery', 'feeling', '{has_interests}', 'interest_self', '{self_discovery,surprise}', 97),
(0, 'If you had to introduce a total beginner to {interest}, where would you start?', 'interest', '{interest}', 'teaching', 'event', '{has_interests}', 'interest_intro', '{teaching,basics}', 98),

-- anchor='why_here' (16 prompts)
(0, 'You said you want to {why_text} — what moment made you decide now was the time?', 'why_here', '{why_text}', 'motivation', 'turning_point', '{has_why}', 'why_moment', '{motivation,decision}', 99),
(0, 'When you think about {why_text}, who''s the first person that comes to mind?', 'why_here', '{why_text}', 'connections', 'people', '{has_why}', 'why_person', '{connections,legacy}', 100),
(0, 'What would it mean to you if you actually accomplished {why_text}?', 'why_here', '{why_text}', 'meaning', 'feeling', '{has_why}', 'why_meaning', '{meaning,purpose}', 101),
(0, 'What''s the one story you''d want to capture first as part of {why_text}?', 'why_here', '{why_text}', 'priorities', 'event', '{has_why}', 'why_first_story', '{priorities,storytelling}', 102),
(0, 'Who do you hope will see or benefit from {why_text} someday?', 'why_here', '{why_text}', 'legacy', 'people', '{has_why}', 'why_audience', '{legacy,family}', 103),
(0, 'Is there someone who inspired you to want to {why_text}?', 'why_here', '{why_text}', 'inspiration', 'people', '{has_why}', 'why_inspiration', '{inspiration,role_models}', 104),
(0, 'What''s a memory that perfectly captures why {why_text} matters to you?', 'why_here', '{why_text}', 'core_memory', 'feeling', '{has_why}', 'why_core_memory', '{core_memory,purpose}', 105),
(0, 'What''s the hardest part about {why_text} that you didn''t expect?', 'why_here', '{why_text}', 'challenges', 'feeling', '{has_why}', 'why_challenge', '{challenges,honesty}', 106),
(0, 'If you could only {why_text} for one person, who would it be?', 'why_here', '{why_text}', 'dedication', 'people', '{has_why}', 'why_one_person', '{dedication,love}', 107),
(0, 'What part of your past feels most important to include when you {why_text}?', 'why_here', '{why_text}', 'curation', 'event', '{has_why}', 'why_important_past', '{curation,reflection}', 108),
(0, 'Is there a version of {why_text} that you''re afraid won''t come out right?', 'why_here', '{why_text}', 'vulnerability', 'feeling', '{has_why}', 'why_fear', '{vulnerability,perfectionism}', 109),
(0, 'What will you feel when {why_text} is actually done?', 'why_here', '{why_text}', 'completion', 'feeling', '{has_why}', 'why_completion', '{completion,relief}', 110),
(0, 'What''s a conversation you''ve had recently that reminded you why you want to {why_text}?', 'why_here', '{why_text}', 'reinforcement', 'event', '{has_why}', 'why_conversation', '{reinforcement,connection}', 111),
(0, 'When did you first realize you wanted to {why_text} — was it sudden or gradual?', 'why_here', '{why_text}', 'origins', 'turning_point', '{has_why}', 'why_realization', '{origins,awareness}', 112),
(0, 'What''s a detail about your life that most people don''t know, but matters for {why_text}?', 'why_here', '{why_text}', 'hidden', 'feeling', '{has_why}', 'why_hidden_detail', '{hidden,authenticity}', 113),
(0, 'If {why_text} could change just one thing for someone you love, what would that be?', 'why_here', '{why_text}', 'impact', 'people', '{has_why}', 'why_impact', '{impact,hope}', 114),

-- anchor='era' (16 prompts)
(0, 'What''s something you believed at 20 that you''ve completely changed your mind about?', 'era', '{}', 'perspective', 'turning_point', '{has_era}', 'era_belief_change', '{perspective,growth}', 115),
(0, 'What''s a lesson you learned in your {decade}s that you wish someone had told you earlier?', 'era', '{decade}', 'wisdom', 'feeling', '{has_era}', 'era_lesson', '{wisdom,hindsight}', 116),
(0, 'What were you obsessed with in your {decade}s that you''d forgotten about until just now?', 'era', '{decade}', 'nostalgia', 'object', '{has_era}', 'era_obsession', '{nostalgia,passions}', 117),
(0, 'What''s a friendship from your {decade}s that shaped who you became?', 'era', '{decade}', 'friendship', 'people', '{has_era}', 'era_friendship', '{friendship,influence}', 118),
(0, 'What did you look like in your {decade}s — and how did you feel about it then?', 'era', '{decade}', 'self_image', 'feeling', '{has_era}', 'era_appearance', '{self_image,identity}', 119),
(0, 'What was your daily routine in your {decade}s?', 'era', '{decade}', 'routine', 'event', '{has_era}', 'era_routine', '{routine,lifestyle}', 120),
(0, 'What''s a risk you took in your {decade}s that still surprises you?', 'era', '{decade}', 'courage', 'event', '{has_era}', 'era_risk', '{courage,surprise}', 121),
(0, 'What was the music of your {decade}s — and what were you doing while it played?', 'era', '{decade}', 'music', 'feeling', '{has_era}', 'era_music', '{music,atmosphere}', 122),
(0, 'Who were you trying to become in your {decade}s?', 'era', '{decade}', 'ambition', 'turning_point', '{has_era}', 'era_ambition', '{ambition,identity}', 123),
(0, 'What''s the funniest thing that happened to you in your {decade}s?', 'era', '{decade}', 'humor', 'event', '{has_era}', 'era_funny', '{humor,stories}', 124),
(0, 'What did love look like in your {decade}s?', 'era', '{decade}', 'love', 'feeling', '{has_era}', 'era_love', '{love,romance}', 125),
(0, 'What were you most afraid of in your {decade}s — and does it still scare you?', 'era', '{decade}', 'fears', 'feeling', '{has_era}', 'era_fear', '{fears,growth}', 126),
(0, 'What''s a place that defined your {decade}s?', 'era', '{decade}', 'places', 'place', '{has_era}', 'era_place', '{places,era}', 127),
(0, 'What job or role did you have in your {decade}s that taught you the most?', 'era', '{decade}', 'work', 'event', '{has_era}', 'era_job', '{work,lessons}', 128),
(0, 'What''s something from your {decade}s that you''d go back and do differently if you could?', 'era', '{decade}', 'regret', 'turning_point', '{has_era}', 'era_redo', '{regret,wisdom}', 129),
(0, 'What''s a moment from your {decade}s that made you realize you were stronger than you thought?', 'era', '{decade}', 'strength', 'turning_point', '{has_era}', 'era_strength', '{strength,resilience}', 130);


-- =============================================================
-- TIER 1 — Foundation (100 prompts)
-- Deeper personalization, references contacts/places/interests.
-- =============================================================

INSERT INTO prompt_seed_library (tier, text, anchor, placeholders, category, angle, requires, anti_repeat_group, snowball_hooks, sort_order) VALUES
(1, 'What was {hometown} like during the holidays when you were a kid?', 'place', '{hometown}', 'holidays', 'place', '{has_places}', 'holiday_hometown', '{holidays,childhood,traditions}', 131),
(1, 'What''s a tradition you had with {person_name} that no one else would understand?', 'person', '{person_name}', 'traditions', 'people', '{has_contacts}', 'person_tradition_unique', '{traditions,bonding}', 132),
(1, 'What''s the most beautiful thing you''ve ever seen in person — not a photo, the real thing?', NULL, '{}', 'beauty', 'feeling', '{answered_3+}', 'most_beautiful', '{beauty,awe}', 133),
(1, 'What''s a job you had early on that taught you something unexpected?', NULL, '{}', 'work', 'event', '{answered_3+}', 'early_job', '{work,growth,lessons}', 134),
(1, 'What''s a family recipe that carries a story with it?', NULL, '{}', 'food', 'object', '{answered_3+}', 'family_recipe', '{food,family,heritage}', 135),
(1, 'What''s the bravest thing you saw {person_name} do?', 'person', '{person_name}', 'courage', 'people', '{has_contacts}', 'person_brave', '{courage,admiration}', 136),
(1, 'What''s a game, sport, or activity you played growing up that kids today have never heard of?', NULL, '{}', 'childhood', 'event', '{answered_3+}', 'childhood_game', '{childhood,play,nostalgia}', 137),
(1, 'What''s the first concert, show, or performance you ever attended?', NULL, '{}', 'culture', 'event', '{answered_3+}', 'first_performance', '{culture,firsts}', 138),
(1, 'What''s a nickname you had that you either loved or hated?', NULL, '{}', 'identity', 'feeling', '{answered_3+}', 'nickname', '{identity,humor}', 139),
(1, 'What''s a lesson {person_name} taught you the hard way?', 'person', '{person_name}', 'lessons', 'people', '{has_contacts}', 'person_hard_lesson', '{lessons,growth}', 140),
(1, 'What did your family''s dinner table look like — who sat where, what was the mood?', NULL, '{}', 'family', 'place', '{answered_3+}', 'dinner_table', '{family,home,routine}', 141),
(1, 'What''s a holiday memory that your family still talks about?', NULL, '{}', 'holidays', 'event', '{answered_3+}', 'holiday_memory', '{holidays,family,stories}', 142),
(1, 'What did you want to be when you grew up — and when did that change?', NULL, '{}', 'dreams', 'turning_point', '{answered_3+}', 'childhood_dream', '{dreams,growing_up}', 143),
(1, 'What''s a road trip or car ride you remember in detail?', NULL, '{}', 'travel', 'event', '{answered_3+}', 'road_trip', '{travel,adventure}', 144),
(1, 'What was the view from your childhood bedroom window?', NULL, '{}', 'childhood', 'place', '{answered_3+}', 'bedroom_view', '{childhood,home,sensory}', 145),
(1, 'What''s a season of life you look back on with complicated feelings?', NULL, '{}', 'reflection', 'feeling', '{answered_3+}', 'complicated_season', '{reflection,ambivalence}', 146),
(1, 'What''s a time {person_name} made you feel seen in a way no one else did?', 'person', '{person_name}', 'connection', 'people', '{has_contacts}', 'person_seen', '{connection,intimacy}', 147),
(1, 'What''s the longest you''ve ever gone without seeing someone you love — and what was the reunion like?', NULL, '{}', 'separation', 'event', '{answered_3+}', 'long_separation', '{separation,reunion,love}', 148),
(1, 'What did Saturday mornings look like when you were growing up?', NULL, '{}', 'childhood', 'event', '{answered_3+}', 'saturday_morning', '{childhood,routine,comfort}', 149),
(1, 'What''s a piece of music that can make you cry, no matter when you hear it?', NULL, '{}', 'music', 'feeling', '{answered_3+}', 'crying_music', '{music,emotion}', 150),
(1, 'What''s the first big purchase you ever made — and how did it feel?', NULL, '{}', 'milestones', 'event', '{answered_3+}', 'first_purchase', '{milestones,independence}', 151),
(1, 'What''s a rule in your family that didn''t exist in anyone else''s?', NULL, '{}', 'family', 'event', '{answered_3+}', 'family_rule', '{family,quirks}', 152),
(1, 'What''s a compliment someone gave you years ago that you still carry with you?', NULL, '{}', 'validation', 'feeling', '{answered_3+}', 'lasting_compliment', '{validation,self_worth}', 153),
(1, 'What''s a pet you had that was more than just a pet?', NULL, '{}', 'animals', 'people', '{answered_3+}', 'beloved_pet', '{animals,love,loss}', 154),
(1, 'What''s a superstition or habit you picked up from someone in your family?', NULL, '{}', 'family', 'object', '{answered_3+}', 'family_superstition', '{family,habits,heritage}', 155),
(1, 'What''s a summer that stands out from all the others?', NULL, '{}', 'seasons', 'event', '{answered_3+}', 'standout_summer', '{seasons,nostalgia}', 156),
(1, 'What''s the first movie you remember seeing in a theater?', NULL, '{}', 'culture', 'event', '{answered_3+}', 'first_movie', '{culture,firsts,childhood}', 157),
(1, 'What''s a promise you made to yourself that you actually kept?', NULL, '{}', 'integrity', 'turning_point', '{answered_3+}', 'kept_promise', '{integrity,determination}', 158),
(1, 'What''s a skill you learned from watching someone else — not from a class?', NULL, '{}', 'learning', 'event', '{answered_3+}', 'observed_skill', '{learning,mentors}', 159),
(1, 'What''s the longest walk you ever took, and what were you thinking about?', NULL, '{}', 'contemplation', 'event', '{answered_3+}', 'longest_walk', '{contemplation,movement}', 160),
(1, 'What''s a conversation you wish you could have recorded?', NULL, '{}', 'moments', 'event', '{answered_3+}', 'wish_recorded', '{moments,wisdom}', 161),
(1, 'What was your first car like — and where did it take you?', NULL, '{}', 'milestones', 'object', '{answered_3+}', 'first_car', '{milestones,freedom,adventure}', 162),
(1, 'What did you and your best friend do after school that felt like the whole world?', NULL, '{}', 'friendship', 'event', '{answered_3+}', 'after_school', '{friendship,childhood}', 163),
(1, 'What''s a time you pretended to be fine but weren''t — and who noticed?', NULL, '{}', 'vulnerability', 'feeling', '{answered_3+}', 'pretending_fine', '{vulnerability,perception}', 164),
(1, 'What''s a project or creation you poured yourself into?', NULL, '{}', 'creation', 'event', '{answered_3+}', 'passion_project', '{creation,pride,dedication}', 165),
(1, 'What''s a morning routine you miss from an earlier time in your life?', NULL, '{}', 'routine', 'event', '{answered_3+}', 'missed_routine', '{routine,nostalgia}', 166),
(1, 'What did it feel like the first time you held your child, niece, nephew, or someone tiny and new?', NULL, '{}', 'family', 'feeling', '{answered_3+}', 'holding_baby', '{family,tenderness,awe}', 167),
(1, 'What''s a gift you gave that you were especially proud of?', NULL, '{}', 'generosity', 'object', '{answered_3+}', 'proud_gift', '{generosity,thoughtfulness}', 168),
(1, 'What''s a teacher or coach who changed something in you?', NULL, '{}', 'mentors', 'people', '{answered_3+}', 'teacher_impact', '{mentors,education}', 169),
(1, 'What''s the scariest thing that happened to you that you can laugh about now?', NULL, '{}', 'resilience', 'event', '{answered_3+}', 'scary_now_funny', '{resilience,humor,time}', 170),
(1, 'What''s a weekend trip that punched way above its weight in memories?', NULL, '{}', 'travel', 'event', '{answered_3+}', 'weekend_trip', '{travel,surprise}', 171),
(1, 'What''s a TV show or movie that your whole family would watch together?', NULL, '{}', 'family', 'object', '{answered_3+}', 'family_show', '{family,culture,togetherness}', 172),
(1, 'What''s the most memorable meal someone cooked for you?', NULL, '{}', 'food', 'feeling', '{answered_3+}', 'cooked_meal', '{food,love,care}', 173),
(1, 'What was your first day at a new school or job really like?', NULL, '{}', 'transitions', 'event', '{answered_3+}', 'first_day', '{transitions,anxiety,beginnings}', 174),
(1, 'What''s something you did as a teenager that still makes you cringe — in a good way?', NULL, '{}', 'youth', 'event', '{answered_3+}', 'teen_cringe', '{youth,humor,growth}', 175),
(1, 'What''s a phone call you''ll never forget?', NULL, '{}', 'moments', 'event', '{answered_3+}', 'memorable_call', '{moments,surprise}', 176),
(1, 'What''s a book that found you at exactly the right time?', NULL, '{}', 'culture', 'object', '{answered_3+}', 'right_time_book', '{culture,timing}', 177),
(1, 'What''s a time you felt completely out of your element — and what happened?', NULL, '{}', 'discomfort', 'event', '{answered_3+}', 'out_of_element', '{discomfort,growth}', 178),
(1, 'What''s the most thoughtful thing anyone has ever done for you?', NULL, '{}', 'gratitude', 'feeling', '{answered_3+}', 'most_thoughtful', '{gratitude,love}', 179),
(1, 'What''s a chore or task you actually used to enjoy — and why?', NULL, '{}', 'routine', 'feeling', '{answered_3+}', 'enjoyable_chore', '{routine,meditation}', 180),
(1, 'What''s the view from a window you''ll never forget?', NULL, '{}', 'sensory', 'place', '{answered_3+}', 'window_view', '{sensory,beauty}', 181),
(1, 'What''s a lie you told as a kid that you still remember?', NULL, '{}', 'childhood', 'event', '{answered_3+}', 'childhood_lie', '{childhood,innocence,humor}', 182),
(1, 'Who''s someone you''d want in the room if things went sideways?', NULL, '{}', 'trust', 'people', '{answered_3+}', 'trust_person', '{trust,reliability}', 183),
(1, 'What''s a dance, a hug, or a moment of physical contact you remember vividly?', NULL, '{}', 'physical', 'feeling', '{answered_3+}', 'vivid_contact', '{physical,emotion}', 184),
(1, 'What''s a storm — literal or figurative — that you got through together with someone?', NULL, '{}', 'resilience', 'event', '{answered_3+}', 'storm_together', '{resilience,bonding}', 185),
(1, 'What''s the best party or gathering you ever went to?', NULL, '{}', 'celebration', 'event', '{answered_3+}', 'best_party', '{celebration,joy}', 186),
(1, 'What''s a bedtime routine from your childhood that you can still feel?', NULL, '{}', 'childhood', 'feeling', '{answered_3+}', 'bedtime_routine', '{childhood,comfort,safety}', 187),
(1, 'What''s a photograph of you that captures who you really were at that moment?', NULL, '{}', 'identity', 'object', '{answered_3+}', 'capturing_photo', '{identity,truth}', 188),
(1, 'What''s the kindest thing you ever did that no one knows about?', NULL, '{}', 'kindness', 'event', '{answered_3+}', 'secret_kindness', '{kindness,character}', 189),
(1, 'What''s a room you spent a lot of time in that you can still walk through in your mind?', NULL, '{}', 'nostalgia', 'place', '{answered_3+}', 'mental_room', '{nostalgia,detail}', 190),
(1, 'What was the first thing you ever saved up to buy?', NULL, '{}', 'milestones', 'object', '{answered_3+}', 'saved_up', '{milestones,patience}', 191),
(1, 'What''s a wedding, funeral, or ceremony you''ll always remember?', NULL, '{}', 'ceremony', 'event', '{answered_3+}', 'memorable_ceremony', '{ceremony,emotions}', 192),
(1, 'What''s the best conversation you ever had in a car?', NULL, '{}', 'connection', 'event', '{answered_3+}', 'car_conversation', '{connection,intimacy}', 193),
(1, 'What''s a scar — physical or otherwise — that has a story behind it?', NULL, '{}', 'stories', 'object', '{answered_3+}', 'scar_story', '{stories,resilience}', 194),
(1, 'What''s a place you used to eat at that''s closed now, and what did you always order?', NULL, '{}', 'food', 'place', '{answered_3+}', 'closed_restaurant', '{food,nostalgia,loss}', 195),
(1, 'What''s a friendship that started in the most unexpected way?', NULL, '{}', 'friendship', 'people', '{answered_3+}', 'unexpected_friend', '{friendship,serendipity}', 196),
(1, 'What''s a sound your house made that you didn''t realize you''d miss?', NULL, '{}', 'sensory', 'feeling', '{answered_3+}', 'house_sound', '{sensory,home,nostalgia}', 197),
(1, 'What''s a time you were wrong about someone — in a good way?', NULL, '{}', 'perception', 'people', '{answered_3+}', 'wrong_about_someone', '{perception,surprise}', 198),
(1, 'What''s a secret spot you had as a kid that was all yours?', NULL, '{}', 'childhood', 'place', '{answered_3+}', 'secret_spot', '{childhood,solitude,imagination}', 199),
(1, 'What did your grandparents'' house smell like?', NULL, '{}', 'family', 'feeling', '{answered_3+}', 'grandparent_smell', '{family,sensory,nostalgia}', 200),
(1, 'What''s a piece of clothing from your past that you wish you still had?', NULL, '{}', 'fashion', 'object', '{answered_3+}', 'lost_clothing', '{fashion,nostalgia}', 201),
(1, 'What''s a time when the weather matched exactly how you were feeling?', NULL, '{}', 'atmosphere', 'feeling', '{answered_3+}', 'weather_matched', '{atmosphere,pathetic_fallacy}', 202),
(1, 'What''s a handwritten note or letter you still have somewhere?', NULL, '{}', 'keepsakes', 'object', '{answered_3+}', 'saved_letter', '{keepsakes,communication}', 203),
(1, 'What''s a meal you ate alone that you actually enjoyed?', NULL, '{}', 'solitude', 'event', '{answered_3+}', 'solo_meal', '{solitude,self_care}', 204),
(1, 'What''s something you rehearsed saying but when the moment came, said something completely different?', NULL, '{}', 'honesty', 'event', '{answered_3+}', 'unrehearsed', '{honesty,spontaneity}', 205),
(1, 'What''s a New Year''s Eve you actually remember — not for the party, for how you felt?', NULL, '{}', 'holidays', 'feeling', '{answered_3+}', 'new_years_feeling', '{holidays,reflection}', 206),
(1, 'What''s a smell from a kitchen — yours or someone else''s — that you could recognize anywhere?', NULL, '{}', 'sensory', 'feeling', '{answered_3+}', 'kitchen_smell', '{sensory,food,home}', 207),
(1, 'What''s the most important thing in the room where you''re sitting right now — and why?', NULL, '{}', 'present', 'object', '{answered_3+}', 'room_object', '{present,meaning}', 208),
(1, 'What''s a story your family tells about you that you don''t actually remember?', NULL, '{}', 'family', 'event', '{answered_3+}', 'family_story', '{family,identity}', 209),
(1, 'What was your first real job like — the people, the place, the feeling of it?', NULL, '{}', 'work', 'event', '{answered_3+}', 'first_real_job', '{work,coming_of_age}', 210),
(1, 'What''s a song that reminds you of a specific drive or journey?', NULL, '{}', 'music', 'feeling', '{answered_3+}', 'journey_song', '{music,travel}', 211),
(1, 'What''s a small thing someone does for you regularly that you never take for granted?', NULL, '{}', 'gratitude', 'feeling', '{answered_3+}', 'daily_gratitude', '{gratitude,love,routine}', 212),
(1, 'What''s the closest you''ve come to a miracle — something that probably shouldn''t have happened but did?', NULL, '{}', 'wonder', 'event', '{answered_3+}', 'near_miracle', '{wonder,luck}', 213),
(1, 'What''s a thing you do exactly the way one of your parents did it?', NULL, '{}', 'heritage', 'event', '{answered_3+}', 'parent_echo', '{heritage,patterns}', 214),
(1, 'What''s a rainy day from your past that was actually perfect?', NULL, '{}', 'weather', 'event', '{answered_3+}', 'perfect_rain', '{weather,comfort}', 215),
(1, 'What''s the most alive you''ve ever felt?', NULL, '{}', 'vitality', 'feeling', '{answered_3+}', 'most_alive', '{vitality,peak_experience}', 216),
(1, 'What''s a toy or game from childhood that you could still describe in perfect detail?', NULL, '{}', 'childhood', 'object', '{answered_3+}', 'childhood_toy', '{childhood,detail,play}', 217),
(1, 'What''s a Sunday afternoon activity that defined a chapter of your life?', NULL, '{}', 'routine', 'event', '{answered_3+}', 'sunday_activity', '{routine,chapters}', 218),
(1, 'What''s the most important thing your best friend doesn''t know about you?', NULL, '{}', 'secrets', 'feeling', '{answered_3+}', 'friend_doesnt_know', '{secrets,vulnerability}', 219),
(1, 'What''s a time you showed up for someone in a way that cost you something?', NULL, '{}', 'sacrifice', 'event', '{answered_3+}', 'showed_up', '{sacrifice,loyalty}', 220),
(1, 'What''s a sunset, sunrise, or sky you can still picture?', NULL, '{}', 'nature', 'place', '{answered_3+}', 'memorable_sky', '{nature,beauty}', 221),
(1, 'What''s the weirdest thing you''ve ever collected?', NULL, '{}', 'quirks', 'object', '{answered_3+}', 'weird_collection', '{quirks,personality}', 222),
(1, 'What''s a time silence said more than words?', NULL, '{}', 'communication', 'feeling', '{answered_3+}', 'meaningful_silence', '{communication,depth}', 223),
(1, 'What''s a trip that was supposed to be fun but turned into something more meaningful?', NULL, '{}', 'travel', 'event', '{answered_3+}', 'meaningful_trip', '{travel,depth}', 224),
(1, 'What''s a sound that still means "home" to you?', NULL, '{}', 'sensory', 'feeling', '{answered_3+}', 'home_sound', '{sensory,home,belonging}', 225),
(1, 'What''s a birthday you remember not for the celebration but for something else entirely?', NULL, '{}', 'birthdays', 'event', '{answered_3+}', 'off_script_birthday', '{birthdays,surprise}', 226),
(1, 'What''s a piece of advice you gave someone that you should take yourself?', NULL, '{}', 'wisdom', 'feeling', '{answered_3+}', 'own_advice', '{wisdom,irony}', 227),
(1, 'What''s a craft, recipe, or technique that was passed down to you?', NULL, '{}', 'heritage', 'object', '{answered_3+}', 'passed_down', '{heritage,family,skills}', 228),
(1, 'What did the air smell like during the best season in the place you grew up?', NULL, '{}', 'sensory', 'feeling', '{answered_3+}', 'season_smell', '{sensory,seasons,childhood}', 229),
(1, 'What''s a dream — sleeping dream — that you still remember years later?', NULL, '{}', 'subconscious', 'feeling', '{answered_3+}', 'remembered_dream', '{subconscious,mystery}', 230);


-- =============================================================
-- TIER 2 — Connection (120 prompts)
-- References relationships deeply, starts building threads.
-- =============================================================

INSERT INTO prompt_seed_library (tier, text, anchor, placeholders, category, angle, requires, anti_repeat_group, snowball_hooks, sort_order) VALUES
(2, 'What''s a conversation with {person_name} you replay in your head sometimes?', 'person', '{person_name}', 'connection', 'people', '{has_contacts,answered_5+}', 'replayed_convo', '{connection,significance}', 231),
(2, 'What''s a trip you took that changed how you think about something?', NULL, '{}', 'travel', 'event', '{answered_5+}', 'perspective_trip', '{travel,growth}', 232),
(2, 'What did you and {person_name} fight about — and what was really underneath it?', 'person', '{person_name}', 'conflict', 'people', '{has_contacts,answered_5+}', 'person_conflict', '{conflict,depth}', 233),
(2, 'What''s a place you went with {person_name} that you associate entirely with them?', 'person', '{person_name}', 'places', 'place', '{has_contacts,answered_5+}', 'person_place', '{places,association}', 234),
(2, 'What''s a decision you made to protect someone, even though it was hard?', NULL, '{}', 'protection', 'event', '{answered_5+}', 'protective_decision', '{protection,sacrifice}', 235),
(2, 'What''s the most honest conversation you''ve ever had?', NULL, '{}', 'honesty', 'event', '{answered_5+}', 'honest_convo', '{honesty,vulnerability}', 236),
(2, 'What did {person_name} look like the last time you really looked at them?', 'person', '{person_name}', 'observation', 'people', '{has_contacts,answered_5+}', 'person_look', '{observation,attention}', 237),
(2, 'What''s a moment when you realized {person_name} needed you, even if they didn''t say it?', 'person', '{person_name}', 'intuition', 'people', '{has_contacts,answered_5+}', 'person_needed', '{intuition,care}', 238),
(2, 'What''s a place you lived that you didn''t appreciate until you left?', NULL, '{}', 'gratitude', 'place', '{answered_5+}', 'underappreciated_place', '{gratitude,hindsight}', 239),
(2, 'What''s a secret language — a look, a phrase, a gesture — that only you and someone close understand?', NULL, '{}', 'intimacy', 'people', '{answered_5+}', 'secret_language', '{intimacy,connection}', 240),
(2, 'What''s a photograph you''ve taken that means more to you than it would to anyone else?', NULL, '{}', 'photography', 'object', '{answered_5+}', 'personal_photo', '{photography,meaning}', 241),
(2, 'What''s a time you had to choose between two people or paths — and how did you decide?', NULL, '{}', 'choices', 'turning_point', '{answered_5+}', 'fork_in_road', '{choices,consequences}', 242),
(2, 'What''s a moment you shared with {person_name} that bonded you in a way nothing else could?', 'person', '{person_name}', 'bonding', 'event', '{has_contacts,answered_5+}', 'person_bond', '{bonding,depth}', 243),
(2, 'What''s a fear you''ve never told anyone about?', NULL, '{}', 'vulnerability', 'feeling', '{answered_5+}', 'secret_fear', '{vulnerability,trust}', 244),
(2, 'What''s a promise someone made to you that they kept against all odds?', NULL, '{}', 'trust', 'people', '{answered_5+}', 'kept_promise_other', '{trust,loyalty}', 245),
(2, 'What''s the most uncomfortable silence you''ve sat through — and what happened after?', NULL, '{}', 'tension', 'event', '{answered_5+}', 'uncomfortable_silence', '{tension,resolution}', 246),
(2, 'What''s something you know about {person_name} that they''d be surprised you noticed?', 'person', '{person_name}', 'observation', 'people', '{has_contacts,answered_5+}', 'person_noticed', '{observation,attention}', 247),
(2, 'What''s a night you stayed up way too late — and it was completely worth it?', NULL, '{}', 'spontaneity', 'event', '{answered_5+}', 'late_night', '{spontaneity,energy}', 248),
(2, 'What''s a meal you cooked for someone that was really an act of love?', NULL, '{}', 'love', 'event', '{answered_5+}', 'love_meal', '{love,food,care}', 249),
(2, 'What''s a thing about {person_name} that drives you crazy but you''d miss if it were gone?', 'person', '{person_name}', 'acceptance', 'people', '{has_contacts,answered_5+}', 'person_annoyance', '{acceptance,love}', 250),
(2, 'What''s a piece of your story that you think people would be surprised to learn?', NULL, '{}', 'hidden', 'event', '{answered_5+}', 'surprising_story', '{hidden,identity}', 251),
(2, 'What''s a room in your current home that has become something you didn''t plan?', NULL, '{}', 'home', 'place', '{answered_5+}', 'evolved_room', '{home,organic}', 252),
(2, 'What''s the longest letter, email, or text you ever wrote — and what were you trying to say?', NULL, '{}', 'communication', 'event', '{answered_5+}', 'long_message', '{communication,urgency}', 253),
(2, 'What''s an argument you lost that you now realize you should have lost?', NULL, '{}', 'humility', 'turning_point', '{answered_5+}', 'lost_argument', '{humility,growth}', 254),
(2, 'What''s a photo of {person_name} that captures exactly who they are?', 'person', '{person_name}', 'essence', 'people', '{has_contacts,answered_5+}', 'person_photo', '{essence,truth}', 255),
(2, 'What''s a tradition you started yourself — not one you inherited?', NULL, '{}', 'creation', 'event', '{answered_5+}', 'new_tradition', '{creation,intention}', 256),
(2, 'What''s the hardest apology you ever had to give?', NULL, '{}', 'accountability', 'event', '{answered_5+}', 'hard_apology', '{accountability,growth}', 257),
(2, 'What''s a moment of unexpected beauty you stumbled into?', NULL, '{}', 'beauty', 'feeling', '{answered_5+}', 'unexpected_beauty', '{beauty,surprise}', 258),
(2, 'What does {person_name} do when they think nobody''s watching?', 'person', '{person_name}', 'observation', 'people', '{has_contacts,answered_5+}', 'person_unguarded', '{observation,authenticity}', 259),
(2, 'What''s a habit from your twenties that you either kept or deliberately broke?', NULL, '{}', 'habits', 'event', '{answered_5+}', 'twenties_habit', '{habits,evolution}', 260),
(2, 'What''s a question you''ve been asked in life that you''re still figuring out the answer to?', NULL, '{}', 'existential', 'feeling', '{answered_5+}', 'open_question', '{existential,searching}', 261),
(2, 'What''s the best hand-me-down you ever received — and from whom?', NULL, '{}', 'heritage', 'object', '{answered_5+}', 'hand_me_down', '{heritage,connection}', 262),
(2, 'What''s a morning you woke up and knew everything was about to change?', NULL, '{}', 'premonition', 'turning_point', '{answered_5+}', 'premonition_morning', '{premonition,change}', 263),
(2, 'What does the word "home" mean to you — not the place, the feeling?', NULL, '{}', 'belonging', 'feeling', '{answered_5+}', 'home_feeling', '{belonging,identity}', 264),
(2, 'What''s the most {person_name} thing {person_name} has ever done?', 'person', '{person_name}', 'character', 'people', '{has_contacts,answered_5+}', 'person_quintessential', '{character,identity}', 265),
(2, 'What''s a failure that taught you more than any success?', NULL, '{}', 'failure', 'event', '{answered_5+}', 'instructive_failure', '{failure,wisdom}', 266),
(2, 'What''s a time you witnessed something you weren''t supposed to see?', NULL, '{}', 'witness', 'event', '{answered_5+}', 'unseen_witness', '{witness,secrets}', 267),
(2, 'What''s a compliment you got that made you uncomfortable because it was too accurate?', NULL, '{}', 'discomfort', 'feeling', '{answered_5+}', 'accurate_compliment', '{discomfort,truth}', 268),
(2, 'What''s a talent or ability of {person_name} that not enough people appreciate?', 'person', '{person_name}', 'admiration', 'people', '{has_contacts,answered_5+}', 'person_talent', '{admiration,recognition}', 269),
(2, 'What''s a place you two always ended up at, no matter what the original plan was?', NULL, '{}', 'patterns', 'place', '{answered_5+}', 'default_place', '{patterns,comfort}', 270),
(2, 'What''s a time your body knew something before your mind did?', NULL, '{}', 'intuition', 'feeling', '{answered_5+}', 'body_knowing', '{intuition,awareness}', 271),
(2, 'What''s a small thing you do every day that connects you to someone you love?', NULL, '{}', 'ritual', 'event', '{answered_5+}', 'daily_connection', '{ritual,love}', 272),
(2, 'What''s the most {person_name} has ever laughed — what caused it?', 'person', '{person_name}', 'joy', 'people', '{has_contacts,answered_5+}', 'person_laugh', '{joy,humor}', 273),
(2, 'What''s a lie you told that you still feel complicated about?', NULL, '{}', 'honesty', 'feeling', '{answered_5+}', 'complicated_lie', '{honesty,guilt}', 274),
(2, 'What''s a song {person_name} loved that you now can''t hear without thinking of them?', 'person', '{person_name}', 'music', 'object', '{has_contacts,answered_5+}', 'person_song', '{music,association}', 275),
(2, 'What''s a time you felt genuinely proud of someone else — not politely proud, deeply proud?', NULL, '{}', 'pride', 'feeling', '{answered_5+}', 'proud_of_other', '{pride,love}', 276),
(2, 'What''s the hardest goodbye you had to say more than once?', NULL, '{}', 'loss', 'event', '{answered_5+}', 'repeated_goodbye', '{loss,endurance}', 277),
(2, 'What''s a holiday that went off the rails — and became better for it?', NULL, '{}', 'holidays', 'event', '{answered_5+}', 'holiday_offscript', '{holidays,chaos,joy}', 278),
(2, 'What''s a lesson you learned from {person_name} that they never meant to teach?', 'person', '{person_name}', 'lessons', 'people', '{has_contacts,answered_5+}', 'person_accidental_lesson', '{lessons,modeling}', 279),
(2, 'What''s a time you forgave someone before you were ready?', NULL, '{}', 'forgiveness', 'turning_point', '{answered_5+}', 'early_forgiveness', '{forgiveness,process}', 280),
(2, 'What''s a community or group you belonged to that shaped you more than you expected?', NULL, '{}', 'community', 'people', '{answered_5+}', 'shaping_community', '{community,identity}', 281),
(2, 'What''s a piece of art, music, or writing that said something you couldn''t?', NULL, '{}', 'expression', 'object', '{answered_5+}', 'art_spoke', '{expression,resonance}', 282),
(2, 'What''s a time you sat with someone in pain and just being there was enough?', NULL, '{}', 'presence', 'event', '{answered_5+}', 'sitting_with_pain', '{presence,compassion}', 283),
(2, 'What''s the view from the place where you''ve done your best thinking?', NULL, '{}', 'reflection', 'place', '{answered_5+}', 'thinking_spot', '{reflection,solitude}', 284),
(2, 'What''s a moment you chose kindness when it would have been easier not to?', NULL, '{}', 'character', 'event', '{answered_5+}', 'chose_kindness', '{character,integrity}', 285),
(2, 'What''s a secret you and {person_name} share that still makes you smile?', 'person', '{person_name}', 'secrets', 'people', '{has_contacts,answered_5+}', 'person_secret', '{secrets,bonding}', 286),
(2, 'What''s a time you saw your parent not as your parent but as a person with their own story?', NULL, '{}', 'family', 'turning_point', '{answered_5+}', 'parent_as_person', '{family,empathy}', 287),
(2, 'What''s a scent that immediately takes you to a specific moment with a specific person?', NULL, '{}', 'sensory', 'feeling', '{answered_5+}', 'scent_person', '{sensory,association}', 288),
(2, 'What''s something you built, fixed, or made that solved a problem nobody else saw?', NULL, '{}', 'resourcefulness', 'object', '{answered_5+}', 'problem_solved', '{resourcefulness,creativity}', 289),
(2, 'What does {person_name}''s handwriting look like — and what does that tell you about them?', 'person', '{person_name}', 'detail', 'people', '{has_contacts,answered_5+}', 'person_handwriting', '{detail,character}', 290),
(2, 'What''s a time you put something in writing that you couldn''t say out loud?', NULL, '{}', 'expression', 'event', '{answered_5+}', 'written_not_spoken', '{expression,vulnerability}', 291),
(2, 'What''s a place you associate with a specific emotion — not a memory, an emotion?', NULL, '{}', 'association', 'place', '{answered_5+}', 'emotion_place', '{association,feeling}', 292),
(2, 'What''s the strangest coincidence that''s ever happened to you?', NULL, '{}', 'fate', 'event', '{answered_5+}', 'strange_coincidence', '{fate,wonder}', 293),
(2, 'What''s a time someone''s face told you everything you needed to know?', NULL, '{}', 'perception', 'people', '{answered_5+}', 'face_told_all', '{perception,truth}', 294),
(2, 'What''s a time you changed your mind in the middle of doing something — and it mattered?', NULL, '{}', 'pivots', 'turning_point', '{answered_5+}', 'mid_pivot', '{pivots,courage}', 295),
(2, 'What''s a gift {person_name} gave you that was so perfect it hurt a little?', 'person', '{person_name}', 'gifts', 'object', '{has_contacts,answered_5+}', 'person_gift', '{gifts,being_known}', 296),
(2, 'What''s a neighborhood sound that would unlock a flood of memories if you heard it now?', NULL, '{}', 'sensory', 'feeling', '{answered_5+}', 'neighborhood_sound', '{sensory,nostalgia}', 297),
(2, 'What''s an heirloom or object in your family that carries more weight than its size?', NULL, '{}', 'heritage', 'object', '{answered_5+}', 'family_heirloom', '{heritage,weight}', 298),
(2, 'What''s a time someone showed you grace when you didn''t deserve it?', NULL, '{}', 'grace', 'feeling', '{answered_5+}', 'undeserved_grace', '{grace,humility}', 299),
(2, 'What''s the most alive {person_name} has ever seemed — what were they doing?', 'person', '{person_name}', 'vitality', 'people', '{has_contacts,answered_5+}', 'person_alive', '{vitality,essence}', 300),
(2, 'What''s a sound from nature that has personal meaning for you?', NULL, '{}', 'nature', 'feeling', '{answered_5+}', 'nature_sound', '{nature,meaning}', 301),
(2, 'What''s a boundary you set that changed a relationship for the better?', NULL, '{}', 'boundaries', 'turning_point', '{answered_5+}', 'healthy_boundary', '{boundaries,growth}', 302),
(2, 'What''s a moment of public embarrassment that turned into something wonderful?', NULL, '{}', 'embarrassment', 'event', '{answered_5+}', 'embarrassment_win', '{embarrassment,redemption}', 303),
(2, 'What''s the last thing you and {person_name} talked about that really mattered?', 'person', '{person_name}', 'depth', 'people', '{has_contacts,answered_5+}', 'person_deep_talk', '{depth,connection}', 304),
(2, 'What''s a color that belongs to a specific time in your life?', NULL, '{}', 'synesthesia', 'feeling', '{answered_5+}', 'era_color', '{synesthesia,association}', 305),
(2, 'What''s a ritual — morning, evening, seasonal — that keeps you grounded?', NULL, '{}', 'ritual', 'event', '{answered_5+}', 'grounding_ritual', '{ritual,stability}', 306),
(2, 'What''s the most beautiful voice you''ve ever heard — speaking, not singing?', NULL, '{}', 'beauty', 'people', '{answered_5+}', 'beautiful_voice', '{beauty,presence}', 307),
(2, 'What''s a time someone you barely knew showed up for you in a big way?', NULL, '{}', 'unexpected', 'people', '{answered_5+}', 'acquaintance_showed_up', '{unexpected,kindness}', 308),
(2, 'What''s a physical sensation — warmth, cold, wind — that triggers a specific memory?', NULL, '{}', 'sensory', 'feeling', '{answered_5+}', 'physical_trigger', '{sensory,memory}', 309),
(2, 'What''s a situation where you had to be the strong one — and what did that cost you?', NULL, '{}', 'strength', 'event', '{answered_5+}', 'being_strong', '{strength,cost}', 310),
(2, 'What''s a time you and {person_name} didn''t need to say anything — just being together was enough?', 'person', '{person_name}', 'presence', 'people', '{has_contacts,answered_5+}', 'person_presence', '{presence,comfort}', 311),
(2, 'What''s a landscape or scene from your life that could be a painting?', NULL, '{}', 'beauty', 'place', '{answered_5+}', 'painting_scene', '{beauty,composition}', 312),
(2, 'What''s a time your intuition saved you from something?', NULL, '{}', 'intuition', 'event', '{answered_5+}', 'intuition_saved', '{intuition,trust}', 313),
(2, 'What''s a time you were someone''s safe place — and how did that feel?', NULL, '{}', 'caregiving', 'feeling', '{answered_5+}', 'safe_place', '{caregiving,responsibility}', 314),
(2, 'What''s the most meaningful thing you''ve inherited — not necessarily the most valuable?', NULL, '{}', 'inheritance', 'object', '{answered_5+}', 'meaningful_inheritance', '{inheritance,legacy}', 315),
(2, 'What''s a day that started ordinary and became unforgettable?', NULL, '{}', 'surprise', 'event', '{answered_5+}', 'ordinary_to_unforgettable', '{surprise,fate}', 316),
(2, 'What''s the thing {person_name} does that tells you they love you without saying it?', 'person', '{person_name}', 'love_language', 'people', '{has_contacts,answered_5+}', 'person_love_language', '{love_language,actions}', 317),
(2, 'What''s a conversation that changed the direction of your career or life?', NULL, '{}', 'pivots', 'event', '{answered_5+}', 'direction_convo', '{pivots,influence}', 318),
(2, 'What''s a texture — fabric, wood, stone — that brings back a memory when you touch it?', NULL, '{}', 'sensory', 'feeling', '{answered_5+}', 'texture_memory', '{sensory,touch}', 319),
(2, 'What''s a time you had to let go of what you wanted so someone else could have what they needed?', NULL, '{}', 'sacrifice', 'turning_point', '{answered_5+}', 'letting_go', '{sacrifice,love}', 320),
(2, 'What''s a time {person_name} stood up for you — did they know how much it meant?', 'person', '{person_name}', 'defense', 'people', '{has_contacts,answered_5+}', 'person_stood_up', '{defense,loyalty}', 321),
(2, 'What''s a door in your life — literal or figurative — that you''re glad you walked through?', NULL, '{}', 'decisions', 'turning_point', '{answered_5+}', 'glad_walked_through', '{decisions,courage}', 322),
(2, 'What''s a night sky you remember — where were you and who were you with?', NULL, '{}', 'nature', 'place', '{answered_5+}', 'night_sky', '{nature,wonder}', 323),
(2, 'What''s the bravest thing you''ve ever said to someone?', NULL, '{}', 'courage', 'event', '{answered_5+}', 'bravest_words', '{courage,truth}', 324),
(2, 'What''s a time you helped someone and it changed you more than it changed them?', NULL, '{}', 'service', 'event', '{answered_5+}', 'helping_changed_me', '{service,transformation}', 325),
(2, 'What''s an object from {person_name} that you still keep close?', 'person', '{person_name}', 'keepsakes', 'object', '{has_contacts,answered_5+}', 'person_keepsake', '{keepsakes,connection}', 326),
(2, 'What''s a time you realized you were repeating a pattern from your family?', NULL, '{}', 'patterns', 'turning_point', '{answered_5+}', 'family_pattern', '{patterns,awareness}', 327),
(2, 'What''s a time laughter broke the tension when nothing else could?', NULL, '{}', 'humor', 'event', '{answered_5+}', 'laughter_rescue', '{humor,relief}', 328),
(2, 'What''s a moment of beauty you witnessed that felt like it was just for you?', NULL, '{}', 'wonder', 'feeling', '{answered_5+}', 'private_beauty', '{wonder,presence}', 329),
(2, 'What''s a mundane errand that became an adventure because of who you were with?', NULL, '{}', 'companionship', 'event', '{answered_5+}', 'errand_adventure', '{companionship,spontaneity}', 330),
(2, 'What did {person_name} smell like? Not perfume or cologne — their actual presence.', 'person', '{person_name}', 'sensory', 'feeling', '{has_contacts,answered_5+}', 'person_scent', '{sensory,intimacy}', 331),
(2, 'What''s a question a child asked you that stopped you in your tracks?', NULL, '{}', 'children', 'event', '{answered_5+}', 'child_question', '{children,wisdom}', 332),
(2, 'What''s a time you chose to be vulnerable and it changed the dynamic entirely?', NULL, '{}', 'vulnerability', 'turning_point', '{answered_5+}', 'chose_vulnerable', '{vulnerability,change}', 333),
(2, 'What''s a time you drove or walked somewhere just to clear your head?', NULL, '{}', 'processing', 'event', '{answered_5+}', 'clearing_head', '{processing,movement}', 334),
(2, 'What''s a word or phrase that only makes sense between you and someone you love?', NULL, '{}', 'language', 'people', '{answered_5+}', 'private_language', '{language,intimacy}', 335),
(2, 'What''s the most peaceful sound you can think of?', NULL, '{}', 'peace', 'feeling', '{answered_5+}', 'peaceful_sound', '{peace,sensory}', 336),
(2, 'What''s a time someone you looked up to let you down — and how did you handle it?', NULL, '{}', 'disillusion', 'people', '{answered_5+}', 'let_down', '{disillusion,maturity}', 337),
(2, 'What''s an old map, ticket, receipt, or stub you saved without really knowing why?', NULL, '{}', 'artifacts', 'object', '{answered_5+}', 'saved_artifact', '{artifacts,nostalgia}', 338),
(2, 'What''s a conversation with {person_name} that you wish had gone differently?', 'person', '{person_name}', 'regret', 'people', '{has_contacts,answered_5+}', 'person_wish_convo', '{regret,honesty}', 339),
(2, 'What''s a tradition that ended — and should it have?', NULL, '{}', 'endings', 'event', '{answered_5+}', 'ended_tradition', '{endings,reflection}', 340),
(2, 'What''s the furthest away from home you''ve ever felt — was it distance or something else?', NULL, '{}', 'distance', 'feeling', '{answered_5+}', 'far_from_home', '{distance,loneliness}', 341),
(2, 'What''s a time you realized you were the older generation and not the younger one?', NULL, '{}', 'aging', 'turning_point', '{answered_5+}', 'generational_shift', '{aging,perspective}', 342),
(2, 'What''s a meal you remember not for the food but for what happened around the table?', NULL, '{}', 'food', 'event', '{answered_5+}', 'table_event', '{food,gathering}', 343),
(2, 'What''s a way you''ve been misunderstood that still bothers you?', NULL, '{}', 'identity', 'feeling', '{answered_5+}', 'misunderstood', '{identity,frustration}', 344),
(2, 'What''s a garden, park, or piece of land that has meaning in your life?', NULL, '{}', 'nature', 'place', '{answered_5+}', 'meaningful_land', '{nature,roots}', 345),
(2, 'What''s a time you held someone''s hand and both of you knew what it meant?', NULL, '{}', 'touch', 'event', '{answered_5+}', 'hand_holding', '{touch,understanding}', 346),
(2, 'What''s a time you had to be the one to say the thing nobody wanted to say?', NULL, '{}', 'courage', 'event', '{answered_5+}', 'hard_truth_teller', '{courage,honesty}', 347),
(2, 'What''s the most comforting thing anyone has ever said to you during a hard time?', NULL, '{}', 'comfort', 'feeling', '{answered_5+}', 'comforting_words', '{comfort,care}', 348),
(2, 'What''s a time you caught yourself becoming someone you didn''t want to be?', NULL, '{}', 'self_awareness', 'turning_point', '{answered_5+}', 'caught_myself', '{self_awareness,course_correction}', 349),
(2, 'What''s a lucky break that changed everything?', NULL, '{}', 'fortune', 'event', '{answered_5+}', 'lucky_break', '{fortune,gratitude}', 350);


-- =============================================================
-- TIER 3 — Depth (100 prompts)
-- Builds on past memories, references themes, asks harder questions.
-- =============================================================

INSERT INTO prompt_seed_library (tier, text, anchor, placeholders, category, angle, requires, anti_repeat_group, snowball_hooks, sort_order) VALUES
(3, 'You shared something about {memory_theme} — was there a part of that story you held back?', NULL, '{memory_theme}', 'deeper', 'feeling', '{answered_10+}', 'held_back', '{depth,honesty}', 351),
(3, 'If you could relive one ordinary Tuesday from ten years ago, which one and why?', NULL, '{}', 'nostalgia', 'event', '{answered_10+}', 'ordinary_tuesday', '{nostalgia,specificity}', 352),
(3, 'What''s a question you wish someone would ask you?', NULL, '{}', 'unspoken', 'feeling', '{answered_10+}', 'wish_asked', '{unspoken,longing}', 353),
(3, 'What''s the thing you''re most afraid of losing — not a person, a quality or ability?', NULL, '{}', 'fear', 'feeling', '{answered_10+}', 'afraid_losing_quality', '{fear,identity}', 354),
(3, 'What''s a version of yourself that you had to leave behind to become who you are now?', NULL, '{}', 'evolution', 'turning_point', '{answered_10+}', 'former_self', '{evolution,shedding}', 355),
(3, 'What''s the conversation you keep almost having but never quite do?', NULL, '{}', 'avoidance', 'feeling', '{answered_10+}', 'almost_conversation', '{avoidance,courage}', 356),
(3, 'When you''re alone with your thoughts at 2 AM, where does your mind go?', NULL, '{}', 'introspection', 'feeling', '{answered_10+}', 'late_night_mind', '{introspection,worry}', 357),
(3, 'What''s a truth about your childhood that took you years to understand?', NULL, '{}', 'childhood', 'turning_point', '{answered_10+}', 'childhood_truth', '{childhood,revelation}', 358),
(3, 'What''s the difference between who you are and who people think you are?', NULL, '{}', 'identity', 'feeling', '{answered_10+}', 'public_private', '{identity,mask}', 359),
(3, 'What''s a sacrifice someone made for you that you can never fully repay?', NULL, '{}', 'gratitude', 'people', '{answered_10+}', 'unrepayable', '{gratitude,debt}', 360),
(3, 'What memory do you return to most often — and has its meaning changed over time?', NULL, '{}', 'recurring', 'feeling', '{answered_10+}', 'most_revisited', '{recurring,interpretation}', 361),
(3, 'What''s the thing you''ve worked hardest to forgive?', NULL, '{}', 'forgiveness', 'feeling', '{answered_10+}', 'hard_forgiveness', '{forgiveness,process}', 362),
(3, 'What''s a part of your story that shaped you more than anyone realizes?', NULL, '{}', 'hidden', 'event', '{answered_10+}', 'hidden_shaper', '{hidden,influence}', 363),
(3, 'What do you think about when you look at your hands?', NULL, '{}', 'reflection', 'feeling', '{answered_10+}', 'looking_at_hands', '{reflection,aging,work}', 364),
(3, 'What would your younger self think of the life you''re living now?', NULL, '{}', 'perspective', 'feeling', '{answered_10+}', 'younger_self_view', '{perspective,assessment}', 365),
(3, 'What''s a wound that healed but left a mark you still feel?', NULL, '{}', 'scars', 'feeling', '{answered_10+}', 'emotional_scar', '{scars,resilience}', 366),
(3, 'What''s the most important thing you''ve never said to someone who''s still alive?', NULL, '{}', 'unsaid', 'people', '{answered_10+}', 'unsaid_living', '{unsaid,urgency}', 367),
(3, 'What pattern do you keep repeating even though you know better?', NULL, '{}', 'patterns', 'turning_point', '{answered_10+}', 'repeated_pattern', '{patterns,awareness}', 368),
(3, 'What does loneliness feel like for you — not the word, the actual sensation?', NULL, '{}', 'loneliness', 'feeling', '{answered_10+}', 'loneliness_sensation', '{loneliness,embodiment}', 369),
(3, 'What''s the most honest thing you could say about your relationship with your father?', NULL, '{}', 'family', 'people', '{answered_10+}', 'father_honest', '{family,truth}', 370),
(3, 'What do you think your life looks like from the outside — and what''s the gap?', NULL, '{}', 'perception', 'feeling', '{answered_10+}', 'outside_vs_inside', '{perception,gap}', 371),
(3, 'What''s a joy in your life that feels too fragile to talk about?', NULL, '{}', 'fragility', 'feeling', '{answered_10+}', 'fragile_joy', '{fragility,superstition}', 372),
(3, 'What''s the most honest thing you could say about your relationship with your mother?', NULL, '{}', 'family', 'people', '{answered_10+}', 'mother_honest', '{family,truth}', 373),
(3, 'What do you pretend doesn''t affect you but actually does — deeply?', NULL, '{}', 'masks', 'feeling', '{answered_10+}', 'hidden_impact', '{masks,vulnerability}', 374),
(3, 'What would you do differently if you knew no one was keeping score?', NULL, '{}', 'freedom', 'event', '{answered_10+}', 'no_score', '{freedom,authenticity}', 375),
(3, 'What''s a regret that you''ve learned to carry without it crushing you?', NULL, '{}', 'regret', 'feeling', '{answered_10+}', 'carried_regret', '{regret,acceptance}', 376),
(3, 'If you could go back and witness one moment from your life as a fly on the wall, which would it be?', NULL, '{}', 'observation', 'event', '{answered_10+}', 'fly_on_wall', '{observation,curiosity}', 377),
(3, 'What''s the most difficult thing about being truly known by someone?', NULL, '{}', 'intimacy', 'feeling', '{answered_10+}', 'being_known', '{intimacy,fear}', 378),
(3, 'What are you still grieving that the world thinks you should be over by now?', NULL, '{}', 'grief', 'feeling', '{answered_10+}', 'ongoing_grief', '{grief,timeline}', 379),
(3, 'What''s a choice you had to make where both options would hurt?', NULL, '{}', 'dilemma', 'event', '{answered_10+}', 'both_hurt', '{dilemma,impossible}', 380),
(3, 'What''s the most tender thing you''ve ever witnessed between two other people?', NULL, '{}', 'tenderness', 'people', '{answered_10+}', 'witnessed_tender', '{tenderness,beauty}', 381),
(3, 'What''s a part of your body that carries a memory?', NULL, '{}', 'embodiment', 'feeling', '{answered_10+}', 'body_memory', '{embodiment,somatic}', 382),
(3, 'What would you tell your children — or the next generation — about what your era was really like?', NULL, '{}', 'legacy', 'event', '{answered_10+}', 'era_truth', '{legacy,witness}', 383),
(3, 'What''s a door you closed that you sometimes wonder about opening again?', NULL, '{}', 'roads', 'feeling', '{answered_10+}', 'closed_door', '{roads,wonder}', 384),
(3, 'What does courage look like in your daily life — not the dramatic kind, the quiet kind?', NULL, '{}', 'courage', 'event', '{answered_10+}', 'quiet_courage', '{courage,daily}', 385),
(3, 'What''s a moment when you felt completely understood — no explanation needed?', NULL, '{}', 'connection', 'feeling', '{answered_10+}', 'understood', '{connection,relief}', 386),
(3, 'What do you think your life would have been like if you''d stayed in {place}?', 'place', '{place}', 'alternate', 'turning_point', '{has_places,answered_10+}', 'what_if_stayed', '{alternate,imagination}', 387),
(3, 'What''s the heaviest secret you ever carried for someone else?', NULL, '{}', 'burden', 'event', '{answered_10+}', 'carried_secret', '{burden,loyalty}', 388),
(3, 'What''s a version of love you had to unlearn?', NULL, '{}', 'love', 'turning_point', '{answered_10+}', 'unlearn_love', '{love,growth}', 389),
(3, 'What''s a time you surprised yourself with your own strength?', NULL, '{}', 'strength', 'event', '{answered_10+}', 'surprised_strength', '{strength,revelation}', 390),
(3, 'What do you need more of in your life right now — and what''s keeping you from it?', NULL, '{}', 'needs', 'feeling', '{answered_10+}', 'current_need', '{needs,obstacles}', 391),
(3, 'What''s a time you had to choose between being right and being kind?', NULL, '{}', 'compassion', 'event', '{answered_10+}', 'right_vs_kind', '{compassion,wisdom}', 392),
(3, 'What''s the most important thing about you that can''t be captured in a photograph?', NULL, '{}', 'essence', 'feeling', '{answered_10+}', 'beyond_photo', '{essence,spirit}', 393),
(3, 'What do you think {person_name} would say if they could see who you''ve become?', 'person', '{person_name}', 'legacy', 'people', '{has_contacts,answered_10+}', 'person_would_say', '{legacy,approval}', 394),
(3, 'What''s a moment you realized your parents had their own inner lives that had nothing to do with you?', NULL, '{}', 'family', 'turning_point', '{answered_10+}', 'parents_inner_life', '{family,maturity}', 395),
(3, 'What do you know now about love that you couldn''t have understood at twenty?', NULL, '{}', 'wisdom', 'feeling', '{answered_10+}', 'love_wisdom', '{wisdom,experience}', 396),
(3, 'What''s a moment of grace in your life that you don''t talk about because it''s too precious?', NULL, '{}', 'sacred', 'feeling', '{answered_10+}', 'precious_grace', '{sacred,protection}', 397),
(3, 'What''s the truest thing you know about yourself?', NULL, '{}', 'truth', 'feeling', '{answered_10+}', 'truest_self', '{truth,identity}', 398),
(3, 'What''s a way your life is richer than it looks from the outside?', NULL, '{}', 'hidden_wealth', 'feeling', '{answered_10+}', 'hidden_richness', '{hidden_wealth,gratitude}', 399),
(3, 'What would you want someone to understand about the decade you''re in right now?', NULL, '{}', 'era', 'feeling', '{answered_10+}', 'current_decade', '{era,truth}', 400),
(3, 'What''s a prayer, wish, or silent request you''ve been carrying?', NULL, '{}', 'spirit', 'feeling', '{answered_10+}', 'silent_prayer', '{spirit,hope}', 401),
(3, 'What''s a compliment you struggle to accept, even though you know it''s true?', NULL, '{}', 'self_image', 'feeling', '{answered_10+}', 'hard_compliment', '{self_image,resistance}', 402),
(3, 'What''s the most peaceful you''ve ever been — and what were the conditions?', NULL, '{}', 'peace', 'feeling', '{answered_10+}', 'peak_peace', '{peace,conditions}', 403),
(3, 'What''s a conversation you''re afraid to have because of what it might reveal?', NULL, '{}', 'avoidance', 'feeling', '{answered_10+}', 'afraid_conversation', '{avoidance,truth}', 404),
(3, 'What have you given up that you''re quietly mourning?', NULL, '{}', 'mourning', 'feeling', '{answered_10+}', 'quiet_mourning', '{mourning,loss}', 405),
(3, 'What''s the gap between what you teach and what you practice?', NULL, '{}', 'hypocrisy', 'feeling', '{answered_10+}', 'teach_vs_practice', '{hypocrisy,growth}', 406),
(3, 'What''s a boundary of yours that took the longest to learn?', NULL, '{}', 'boundaries', 'turning_point', '{answered_10+}', 'slow_boundary', '{boundaries,self_respect}', 407),
(3, 'What do you think you''d do differently in your closest relationships if you had more courage?', NULL, '{}', 'courage', 'people', '{answered_10+}', 'relationship_courage', '{courage,vulnerability}', 408),
(3, 'What''s the question you''re most afraid to answer honestly?', NULL, '{}', 'fear', 'feeling', '{answered_10+}', 'feared_question', '{fear,honesty}', 409),
(3, 'What does trust feel like in your body — not the concept, the physical sensation?', NULL, '{}', 'embodiment', 'feeling', '{answered_10+}', 'trust_in_body', '{embodiment,safety}', 410),
(3, 'What''s the most important thing you''ve learned about yourself in the last year?', NULL, '{}', 'growth', 'turning_point', '{answered_10+}', 'recent_lesson', '{growth,awareness}', 411),
(3, 'What''s something you want your loved ones to know about what this time in your life is really like?', NULL, '{}', 'truth', 'feeling', '{answered_10+}', 'this_time', '{truth,sharing}', 412),
(3, 'What does your face look like when you think no one is watching?', NULL, '{}', 'awareness', 'feeling', '{answered_10+}', 'unguarded_face', '{awareness,default}', 413),
(3, 'What''s a moment you''d be embarrassed for anyone to know how much it meant to you?', NULL, '{}', 'vulnerability', 'feeling', '{answered_10+}', 'secretly_important', '{vulnerability,shame}', 414),
(3, 'What conversation are you still having in your head with someone who isn''t here anymore?', NULL, '{}', 'grief', 'people', '{answered_10+}', 'ongoing_convo', '{grief,continuation}', 415),
(3, 'What''s a way you''ve become gentler over the years?', NULL, '{}', 'softening', 'turning_point', '{answered_10+}', 'becoming_gentler', '{softening,maturity}', 416),
(3, 'What responsibility do you carry that nobody asked you to take on?', NULL, '{}', 'burden', 'feeling', '{answered_10+}', 'voluntary_burden', '{burden,duty}', 417),
(3, 'What makes you feel most like yourself?', NULL, '{}', 'identity', 'feeling', '{answered_10+}', 'most_myself', '{identity,authenticity}', 418),
(3, 'What''s a time you had to be brave for someone else even though you were terrified?', NULL, '{}', 'bravery', 'event', '{answered_10+}', 'brave_for_other', '{bravery,selflessness}', 419),
(3, 'What''s the hardest part of getting older that nobody talks about?', NULL, '{}', 'aging', 'feeling', '{answered_10+}', 'aging_unspoken', '{aging,honesty}', 420),
(3, 'What does your relationship with time look like — do you have enough, too little, or the wrong kind?', NULL, '{}', 'time', 'feeling', '{answered_10+}', 'time_relationship', '{time,urgency}', 421),
(3, 'What would the room feel like if everyone you''ve ever loved was gathered in one place?', NULL, '{}', 'imagination', 'feeling', '{answered_10+}', 'love_gathering', '{imagination,love}', 422),
(3, 'What''s a story about you that gets told wrong — and what''s the real version?', NULL, '{}', 'truth', 'event', '{answered_10+}', 'misheard_story', '{truth,correction}', 423),
(3, 'What do you do with sadness — where does it go when you can''t show it?', NULL, '{}', 'coping', 'feeling', '{answered_10+}', 'hidden_sadness', '{coping,processing}', 424),
(3, 'What was the most clarifying moment of your life — when confusion suddenly became understanding?', NULL, '{}', 'clarity', 'turning_point', '{answered_10+}', 'clarity_moment', '{clarity,epiphany}', 425),
(3, 'What''s a part of your heritage or culture that you''re still learning to understand?', NULL, '{}', 'heritage', 'feeling', '{answered_10+}', 'cultural_learning', '{heritage,identity}', 426),
(3, 'What do you want more credit for than you''ll ever ask for?', NULL, '{}', 'recognition', 'feeling', '{answered_10+}', 'want_credit', '{recognition,pride}', 427),
(3, 'What''s a way you show love that isn''t always recognized as love?', NULL, '{}', 'love', 'event', '{answered_10+}', 'unrecognized_love', '{love,language}', 428),
(3, 'What keeps you up at night — not anxiety, the deep questions?', NULL, '{}', 'existential', 'feeling', '{answered_10+}', 'deep_night', '{existential,wonder}', 429),
(3, 'What have you outgrown that you still miss?', NULL, '{}', 'outgrown', 'feeling', '{answered_10+}', 'outgrown_miss', '{outgrown,nostalgia}', 430),
(3, 'What''s a relationship that made you better at all your other relationships?', NULL, '{}', 'growth', 'people', '{answered_10+}', 'relationship_teacher', '{growth,transfer}', 431),
(3, 'What''s the most important thing about your life that a biography would miss?', NULL, '{}', 'essence', 'feeling', '{answered_10+}', 'beyond_biography', '{essence,inner_life}', 432),
(3, 'What''s the thing you most want to protect in this world?', NULL, '{}', 'protection', 'feeling', '{answered_10+}', 'want_to_protect', '{protection,values}', 433),
(3, 'What would your life sound like if it had a soundtrack?', NULL, '{}', 'creative', 'feeling', '{answered_10+}', 'life_soundtrack', '{creative,identity}', 434),
(3, 'What''s a time you received love in a form you didn''t recognize until later?', NULL, '{}', 'love', 'feeling', '{answered_10+}', 'delayed_love', '{love,recognition}', 435),
(3, 'What''s the most generous interpretation of your hardest year?', NULL, '{}', 'reframing', 'turning_point', '{answered_10+}', 'generous_interpretation', '{reframing,resilience}', 436),
(3, 'What does your silence say — when you go quiet, what are you really thinking?', NULL, '{}', 'communication', 'feeling', '{answered_10+}', 'silence_meaning', '{communication,inner_world}', 437),
(3, 'What''s a way you''ve been loved that you didn''t deserve — and accepted anyway?', NULL, '{}', 'grace', 'feeling', '{answered_10+}', 'undeserved_love', '{grace,acceptance}', 438),
(3, 'If the walls of your childhood home could talk, what story would they tell?', NULL, '{}', 'childhood', 'place', '{answered_10+}', 'walls_talking', '{childhood,home,secrets}', 439),
(3, 'What do you wish you could explain to the people who love you but can''t find the words?', NULL, '{}', 'communication', 'feeling', '{answered_10+}', 'cant_explain', '{communication,frustration}', 440),
(3, 'What''s a time the world felt small — in a beautiful way, not a claustrophobic way?', NULL, '{}', 'wonder', 'feeling', '{answered_10+}', 'small_world', '{wonder,connection}', 441),
(3, 'What''s the one thing about your inner life that would surprise the people closest to you?', NULL, '{}', 'hidden', 'feeling', '{answered_10+}', 'inner_surprise', '{hidden,depth}', 442),
(3, 'What have you learned about loss that you wish you''d known earlier?', NULL, '{}', 'loss', 'feeling', '{answered_10+}', 'loss_wisdom', '{loss,wisdom}', 443),
(3, 'What does home mean to you now that it didn''t mean when you were young?', NULL, '{}', 'evolution', 'feeling', '{answered_10+}', 'home_evolution', '{evolution,maturity}', 444),
(3, 'What would you most want to hear from someone you''ve lost?', NULL, '{}', 'grief', 'people', '{answered_10+}', 'want_to_hear', '{grief,longing}', 445),
(3, 'What''s the thing about you that has stayed the same no matter how much else has changed?', NULL, '{}', 'core', 'feeling', '{answered_10+}', 'constant_self', '{core,identity}', 446),
(3, 'What''s a simple pleasure that has become sacred to you?', NULL, '{}', 'sacred', 'event', '{answered_10+}', 'sacred_pleasure', '{sacred,routine}', 447),
(3, 'What''s the space between who you were and who you are — and how do you bridge it?', NULL, '{}', 'integration', 'turning_point', '{answered_10+}', 'bridging_selves', '{integration,identity}', 448),
(3, 'What''s a way you''re still your parents'' child, no matter how old you get?', NULL, '{}', 'family', 'people', '{answered_10+}', 'still_their_child', '{family,permanence}', 449),
(3, 'What''s the most important promise you''ve made — to yourself or someone else?', NULL, '{}', 'promises', 'feeling', '{answered_10+}', 'important_promise', '{promises,commitment}', 450);


-- =============================================================
-- TIER 4 — Reflection (50 prompts)
-- Synthesize, find patterns, existential beauty.
-- =============================================================

INSERT INTO prompt_seed_library (tier, text, anchor, placeholders, category, angle, requires, anti_repeat_group, snowball_hooks, sort_order) VALUES
(4, 'Looking at everything you''ve shared — what thread do you see running through it all?', NULL, '{}', 'synthesis', 'turning_point', '{answered_20+}', 'common_thread', '{synthesis,pattern}', 451),
(4, 'What would your grandchildren need to know about you to really understand you?', NULL, '{}', 'legacy', 'feeling', '{answered_20+}', 'grandchildren_know', '{legacy,essence}', 452),
(4, 'If your life were a book, what would this chapter be called?', NULL, '{}', 'narrative', 'turning_point', '{answered_20+}', 'chapter_title', '{narrative,framing}', 453),
(4, 'What''s the story of your life that you tell yourself — and is it the true one?', NULL, '{}', 'narrative', 'feeling', '{answered_20+}', 'self_narrative', '{narrative,truth}', 454),
(4, 'If you could leave one sentence behind for someone to find in a hundred years, what would it say?', NULL, '{}', 'legacy', 'feeling', '{answered_20+}', 'one_sentence', '{legacy,distillation}', 455),
(4, 'What do you think is the central lesson your life has been trying to teach you?', NULL, '{}', 'wisdom', 'turning_point', '{answered_20+}', 'central_lesson', '{wisdom,pattern}', 456),
(4, 'What would the title of your memoir be?', NULL, '{}', 'identity', 'feeling', '{answered_20+}', 'memoir_title', '{identity,self_image}', 457),
(4, 'If you could sit with your twenty-year-old self for an hour, what would you say — and what would you ask?', NULL, '{}', 'dialogue', 'people', '{answered_20+}', 'younger_self_convo', '{dialogue,time}', 458),
(4, 'What''s the most important thing you''ve learned about being human?', NULL, '{}', 'wisdom', 'feeling', '{answered_20+}', 'being_human', '{wisdom,universal}', 459),
(4, 'What keeps you going on the days when nothing feels like enough?', NULL, '{}', 'resilience', 'feeling', '{answered_20+}', 'what_sustains', '{resilience,motivation}', 460),
(4, 'What do you want your life to have meant?', NULL, '{}', 'purpose', 'feeling', '{answered_20+}', 'life_meaning', '{purpose,legacy}', 461),
(4, 'If someone made a movie of your life, what scene would you insist they get right?', NULL, '{}', 'pivotal', 'event', '{answered_20+}', 'must_get_right', '{pivotal,truth}', 462),
(4, 'What''s the most important thing you want the people you love to remember about you?', NULL, '{}', 'legacy', 'feeling', '{answered_20+}', 'remembered_for', '{legacy,love}', 463),
(4, 'What question would you most want answered — about your life, your family, anything?', NULL, '{}', 'mystery', 'feeling', '{answered_20+}', 'unanswered_question', '{mystery,curiosity}', 464),
(4, 'What''s the kindest version of your story?', NULL, '{}', 'compassion', 'feeling', '{answered_20+}', 'kindest_version', '{compassion,self_love}', 465),
(4, 'What contradiction in your personality have you made peace with?', NULL, '{}', 'acceptance', 'feeling', '{answered_20+}', 'accepted_contradiction', '{acceptance,wholeness}', 466),
(4, 'What wisdom have you earned the hard way that you hope others can learn more gently?', NULL, '{}', 'teaching', 'feeling', '{answered_20+}', 'hard_won_wisdom', '{teaching,generosity}', 467),
(4, 'What part of your life has been about love — even the parts that didn''t look like it?', NULL, '{}', 'love', 'feeling', '{answered_20+}', 'love_through_all', '{love,reframing}', 468),
(4, 'What''s the thing you''d want someone to know about you if they only had five minutes?', NULL, '{}', 'essence', 'feeling', '{answered_20+}', 'five_minutes', '{essence,priority}', 469),
(4, 'If you could guarantee your loved ones would understand one thing about your life, what would it be?', NULL, '{}', 'communication', 'feeling', '{answered_20+}', 'guarantee_understood', '{communication,legacy}', 470),
(4, 'What''s the throughline between the child you were and the person you are?', NULL, '{}', 'continuity', 'turning_point', '{answered_20+}', 'child_to_adult', '{continuity,identity}', 471),
(4, 'What did you think life would be like — and how is the reality different, better, or more complicated?', NULL, '{}', 'expectations', 'feeling', '{answered_20+}', 'expectations_vs_reality', '{expectations,acceptance}', 472),
(4, 'What''s the bravest thing about the way you''ve lived your life?', NULL, '{}', 'courage', 'feeling', '{answered_20+}', 'bravest_life', '{courage,pride}', 473),
(4, 'What do you think you were put here to learn?', NULL, '{}', 'purpose', 'feeling', '{answered_20+}', 'here_to_learn', '{purpose,spiritual}', 474),
(4, 'What''s a pattern in your life that you didn''t see until just now?', NULL, '{}', 'discovery', 'turning_point', '{answered_20+}', 'new_pattern', '{discovery,awareness}', 475),
(4, 'What would you say to someone going through what you went through — knowing what you know now?', NULL, '{}', 'advice', 'feeling', '{answered_20+}', 'hindsight_advice', '{advice,empathy}', 476),
(4, 'What''s the most important thing that almost didn''t happen?', NULL, '{}', 'fate', 'event', '{answered_20+}', 'almost_didnt', '{fate,gratitude}', 477),
(4, 'How do you want to be loved for the rest of your life?', NULL, '{}', 'love', 'feeling', '{answered_20+}', 'future_love', '{love,desire}', 478),
(4, 'What''s the question you keep circling back to?', NULL, '{}', 'obsession', 'feeling', '{answered_20+}', 'recurring_question', '{obsession,meaning}', 479),
(4, 'What''s the most generous thing someone could assume about the life you''ve lived?', NULL, '{}', 'grace', 'feeling', '{answered_20+}', 'generous_assumption', '{grace,perspective}', 480),
(4, 'What has surprised you most about the person you''ve become?', NULL, '{}', 'surprise', 'turning_point', '{answered_20+}', 'self_surprise', '{surprise,evolution}', 481),
(4, 'If you could only pass down three things to the next generation, what would they be?', NULL, '{}', 'legacy', 'feeling', '{answered_20+}', 'three_things', '{legacy,curation}', 482),
(4, 'What''s the most beautiful ordinary thing about your life right now?', NULL, '{}', 'gratitude', 'feeling', '{answered_20+}', 'beautiful_ordinary', '{gratitude,present}', 483),
(4, 'What''s the love letter you owe your own life?', NULL, '{}', 'self_love', 'feeling', '{answered_20+}', 'love_letter_life', '{self_love,gratitude}', 484),
(4, 'What would you want written on the last page of your story?', NULL, '{}', 'endings', 'feeling', '{answered_20+}', 'last_page', '{endings,meaning}', 485),
(4, 'What do all the people you''ve loved have in common?', NULL, '{}', 'patterns', 'people', '{answered_20+}', 'love_pattern', '{patterns,attraction}', 486),
(4, 'What does a good day look like at this point in your life — and has the answer changed?', NULL, '{}', 'evolution', 'event', '{answered_20+}', 'good_day_now', '{evolution,simplicity}', 487),
(4, 'What''s the thing you''ve built — not a thing, a life, a family, a way of being — that you''re proudest of?', NULL, '{}', 'pride', 'feeling', '{answered_20+}', 'proudest_built', '{pride,creation}', 488),
(4, 'What is your relationship with hope — and how has it changed?', NULL, '{}', 'hope', 'feeling', '{answered_20+}', 'hope_relationship', '{hope,evolution}', 489),
(4, 'What''s the song that could play at the end of your movie — and what mood would it set?', NULL, '{}', 'music', 'feeling', '{answered_20+}', 'closing_song', '{music,tone}', 490),
(4, 'What do you still want to become?', NULL, '{}', 'aspiration', 'feeling', '{answered_20+}', 'still_becoming', '{aspiration,future}', 491),
(4, 'What has been your greatest act of faith — religious or otherwise?', NULL, '{}', 'faith', 'event', '{answered_20+}', 'greatest_faith', '{faith,leap}', 492),
(4, 'What part of your story do you think only you can tell?', NULL, '{}', 'uniqueness', 'feeling', '{answered_20+}', 'only_you', '{uniqueness,authority}', 493),
(4, 'What would you want the people who come after you to know about what it was like to live in this time?', NULL, '{}', 'witness', 'event', '{answered_20+}', 'era_witness', '{witness,history}', 494),
(4, 'If your life had a thesis statement, what would it be?', NULL, '{}', 'synthesis', 'feeling', '{answered_20+}', 'thesis_statement', '{synthesis,distillation}', 495),
(4, 'What''s the most important conversation you''ve had with yourself?', NULL, '{}', 'introspection', 'event', '{answered_20+}', 'self_conversation', '{introspection,growth}', 496),
(4, 'After everything — all the stories, the people, the places, the choices — what do you know for sure?', NULL, '{}', 'certainty', 'feeling', '{answered_20+}', 'know_for_sure', '{certainty,wisdom}', 497),
(4, 'What part of your life has been the most unexpected gift?', NULL, '{}', 'gratitude', 'feeling', '{answered_20+}', 'unexpected_gift', '{gratitude,surprise}', 498),
(4, 'What do you think your life has been about — not what it was supposed to be about, what it actually was?', NULL, '{}', 'truth', 'turning_point', '{answered_20+}', 'actually_about', '{truth,honesty}', 499),
(4, 'When you close your eyes and think about all of this — your whole life, your whole story — what do you feel?', NULL, '{}', 'summation', 'feeling', '{answered_20+}', 'final_feeling', '{summation,wholeness}', 500);
